### ISSUE TITLE
Scanner issues

### ISSUE THREAD

**Issue by ramzini47** [oss-review-toolkit/ort#7900] opened 2023-11-20 15:54 UTC
I am running ort on tekton pipeline and analyzer worked but when I try to do `ort scan -i ort_analyzer/analyzer-result.yml -o ort_scan --skip-excluded` I am getting: 
```
13:47:24.970 [main] ERROR org.ossreviewtoolkit.scanner.scanners.scancode.ScanCode - Could not download 'Maven:com.aayushatharva.brotli4j:brotli4j:1.8.0.redhat-00003': DownloadException: Download failed for 'Maven:com.aayushatharva.brotli4j:brotli4j:1.8.0.redhat-00003'.
Suppressed: DownloadException: Unable to determine a revision to checkout.
Suppressed: DownloadException: Failed to download source artifact.
13:47:25.579 [main] ERROR org.ossreviewtoolkit.scanner.scanners.scancode.ScanCode - Could not download 'Maven:com.aayushatharva.brotli4j:native-linux-x86_64:1.8.0.redhat-00003': DownloadException: Download failed for 'Maven:com.aayushatharva.brotli4j:native-linux-x86_64:1.8.0.redhat-00003'.
Suppressed: DownloadException: Unable to determine a revision to checkout.
Suppressed: DownloadException: No source artifact URL provided for 'Maven:com.aayushatharva.brotli4j:native-linux-x86_64:1.8.0.redhat-00003'.
13:47:26.694 [main] ERROR org.ossreviewtoolkit.scanner.scanners.scancode.ScanCode - Could not download 'Maven:com.fasterxml.jackson.core:jackson-annotations:2.13.4.redhat-00004': DownloadException: Download failed for 'Maven:com.fasterxml.jackson.core:jackson-annotations:2.13.4.redhat-00004'.
Suppressed: DownloadException: Unable to determine a revision to checkout.
Suppressed: DownloadException: Failed to download source artifact.
13:47:27.874 [main] ERROR org.ossreviewtoolkit.scanner.scanners.scancode.ScanCode - Could not download 'Maven:com.fasterxml.jackson.core:jackson-core:2.13.4.redhat-00004': DownloadException: Download failed for 'Maven:com.fasterxml.jackson.core:jackson-core:2.13.4.redhat-00004'.
Suppressed: DownloadException: Unable to determine a revision to checkout.
Suppressed: DownloadException: Failed to download source artifact.
13:47:28.963 [main] ERROR org.ossreviewtoolkit.scanner.scanners.scancode.ScanCode - Could not download 'Maven:com.fasterxml.jackson.core:jackson-databind:2.13.4.2-redhat-00001': DownloadException: Download failed for 'Maven:com.fasterxml.jackson.core:jackson-databind:2.13.4.2-redhat-00001'.
Suppressed: DownloadException: Unable to determine a revision to checkout.
Suppressed: DownloadException: Failed to download source artifact.
13:47:30.096 [main] ERROR org.ossreviewtoolkit.scanner.scanners.scancode.ScanCode - Could not download 'Maven:com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.13.4.redhat-00004': DownloadException: Download failed for 'Maven:com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.13.4.redhat-00004'.
Suppressed: DownloadException: Unable to determine a revision to checkout.
Suppressed: DownloadException: Failed to download source artifact.
13:47:31.231 [main] ERROR org.ossreviewtoolkit.scanner.scanners.scancode.ScanCode - Could not download 'Maven:com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.4.redhat-00004': DownloadException: Download failed for 'Maven:com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.4.redhat-00004'.
Suppressed: DownloadException: Unable to determine a revision to checkout.
Suppressed: DownloadException: Failed to download source artifact.
13:47:32.375 [main] ERROR org.ossreviewtoolkit.scanner.scanners.scancode.ScanCode - Could not download 'Maven:com.fasterxml.jackson.module:jackson-module-parameter-names:2.13.4.redhat-00004': DownloadException: Download failed for 'Maven:com.fasterxml.jackson.module:jackson-module-parameter-names:2.13.4.redhat-00004'.
Suppressed: DownloadException: Unable to determine a revision to checkout.
Suppressed: DownloadException: Failed to download source artifact.
13:47:32.590 [main] ERROR org.ossreviewtoolkit.scanner.scanners.scancode.ScanCode - Could not download 'Maven:com.google.guava:failureaccess:1.0.1.redhat-00004': DownloadException: Download failed for 'Maven:com.google.guava:failureaccess:1.0.1.redhat-00004'.
Suppressed: DownloadException: Unable to determine a revision to checkout.
Suppressed: DownloadException: Failed to download source artifact.
13:47:32.825 [main] ERROR org.ossreviewtoolkit.scanner.scanners.scancode.ScanCode - Could not download 'Maven:com.google.guava:guava:31.1.0.jre-redhat-00004': DownloadException: Download failed for 'Maven:com.google.guava:guava:31.1.0.jre-redhat-00004'.
Suppressed: DownloadException: Unable to determine a revision to checkout.
Suppressed: DownloadException: Failed to download source artifact.
13:59:23.115 [main] WARN  org.ossreviewtoolkit.downloader.vcs.Subversion - Failed to update the Subversion working tree at '/tmp/ort-ScanCode1571366875593154323/Maven/commons-cli/commons-cli/1.4' to revision 'trunk':
SVNException: svn: E160005: Target path '/commons/proper/cli/trunk' does not exist
svn: E175002: REPORT of '/repos/asf/!svn/vcc/default': 500 Internal Server Error (http://svn.apache.org)
```
ort.yaml:
```
ort:

  enableRepositoryPackageConfigurations: true
  enableRepositoryPackageCurations: true
  severeIssueThreshold: ERROR
  severeRuleViolationThreshold: ERROR

  analyzer:
    allowDynamicVersions: true

    # A flag to control whether excluded scopes and paths should be skipped during the analysis.
    skipExcluded: true


  downloader:
    allowMovingRevisions: true


  scanner:
    skipConcluded: true

    archive:
      enabled: true

    createMissingArchives: false


    config:
      # A map from scanner plugin types to the plugin configuration.
      ScanCode:
        options:
          # Command line options that affect the ScanCode output. If changed, stored scan results that were created with
          # different options are not reused.
          commandLine: '--copyright --license --info --strip-root --timeout 300'

          # Command line options that do not affect the ScanCode output.
          commandLineNonConfig: '--processes 4'

          # Criteria for matching stored scan results. These can be configured for any scanner that uses semantic
          # versioning. Note that the 'maxVersion' is exclusive and not part of the range of accepted versions.
          #minVersion: '3.2.1-rc2'
          #maxVersion: '32.0.0'
 

    ignorePatterns: ['**/META-INF/DEPENDENCIES']
```

I am using private maven repository and those artefacts are in there. There is no network issues either. I have similar issue with svn on my local machine with local install of ORT. Any ideas?

**Comment by sschuberth** [comment] 2023-11-20 16:03
> I have similar issue with svn on my local machine with local install of ORT.

Let's close this in favor of your https://github.com/oss-review-toolkit/ort/issues/7899 as the root cause is the same.

**Closed by sschuberth** 2023-11-20 16:03 UTC
