### ISSUE TITLE
Java Exception in scanner after proxy failures

### ISSUE THREAD

**Issue by NicolasToussaint** [oss-review-toolkit/ort#2579] opened 2020-05-05 15:04 UTC
Just tried to scan a Maven project with ORT Scanner with fresh sources, and made ORT crash with the 3 scanners (Licensee, LicenseFinder and ScanCode).

I seem to have qui a few networking problem before that (possibly both Proxy configuration and proxy responsiveness), but in all cases it ends wit the following Exception:

```
16:41:46.355 [main] INFO  org.ossreviewtoolkit.model.OrtResult - Computing excluded projects which may take a while...
Exception in thread "main" java.lang.IllegalArgumentException: The VcsInfo(type=Git, url=https://github.com/spring-projects/spring-boot.git, revision=, resolvedRevision=null, path=spring-boot-starter-parent/_proj
ect) of project 'Maven:com.orange.accessibility:_project:1.0.0' cannot be found in Repository(vcs=VcsInfo(type=, url=, revision=, resolvedRevision=null, path=), vcsProcessed=VcsInfo(type=, url=, revision=, resolv
edRevision=null, path=), nestedRepositories={}, config=RepositoryConfiguration(excludes=Excludes(paths=[], scopes=[]), resolutions=Resolutions(issues=[], ruleViolations=[]), curations=Curations(licenseFindings=[]
))).
        at org.ossreviewtoolkit.model.OrtResult.getFilePathRelativeToAnalyzerRoot(OrtResult.kt:259)
        at org.ossreviewtoolkit.model.OrtResult.getDefinitionFilePathRelativeToAnalyzerRoot(OrtResult.kt:245)
        at org.ossreviewtoolkit.model.config.Excludes.findPathExcludes(Excludes.kt:53)
        at org.ossreviewtoolkit.model.OrtResult$projects$2.invoke(OrtResult.kt:94)
        at org.ossreviewtoolkit.model.OrtResult$projects$2.invoke(OrtResult.kt:43)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.ossreviewtoolkit.model.OrtResult.getProjects(OrtResult.kt)
        at org.ossreviewtoolkit.model.OrtResult.getProject(OrtResult.kt:331)
        at org.ossreviewtoolkit.scanner.Scanner.scanOrtResult(Scanner.kt:121)
        at org.ossreviewtoolkit.commands.ScannerCommand.run(ScannerCommand.kt:151)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:154)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:162)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:14)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:252)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:249)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:267)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:290)
        at org.ossreviewtoolkit.OrtMainKt.main(OrtMain.kt:175)
```
A typical command I've been using: 
`./cli/build/install/ort/bin/ort --info --config /data/ort-home/ort.json scan --download-dir <...>/ScanCode_20200505_081558 --ort-file <...>/010-analyze/analyzer-result.json --scanner ScanCode --output-dir <...>/030-scan_ScanCode_20200505_081558`

**Comment by sschuberth** [comment] 2020-06-02 19:12
I don't think this is specifically proxy related, but could be generally network-flackyness related which might cause some VCS meta-data to be missing.

**Comment by sschuberth** [comment] 2021-09-05 14:36
@maxhbr looks like you're analyzing a local directory that is not under version control (as the `repository:` header does not really contain any data). While that used wot work in the very early days of ORT, support for analyzing directories that are not under version control has been neglected over time. We probably should refuse tun run at all in that case.

**Comment by maxhbr** [comment] 2021-09-06 08:17
The following code, that "fakes" a VCS, does not fix the issue. Ort probably can not handle remotes that are a local path?

```
rm -rf .git .hg # ...
git init
git add .
git config user.email "fakeVCS@sh.invalid"
git config user.name "fakeVCS.sh"
git commit -am"fakeVCS.sh"
git remote add origin "$(pwd)"
```

**Comment by sschuberth** [comment] 2021-09-06 09:44
@maxhbr please continue the discussion in the newly created https://github.com/oss-review-toolkit/ort/issues/4433 as your issue is not related to the issue reported here.

**Comment by sschuberth** [comment] 2023-01-26 15:58
@NicolasToussaint, can you still reproduce the issue, or can we close this?

**Closed** 2023-02-08 20:57 UTC
Labels: bug, help wanted, scanner
