### ISSUE TITLE
Report including not existent licenses

### ISSUE THREAD

**Issue by Franco0700** [oss-review-toolkit/ort#6578] opened 2023-02-28 19:41 UTC
![image](https://user-images.githubusercontent.com/70175704/221960840-32901570-0040-4453-8016-f22cfa8f266d.png)

Here I got that license in the Apprendix, but that license doesn't exist.
I'm running using docker with the following flags
`report -f PdfTemplate -i <input_file> -o <output_folder>`
Also there are other no existent licenses with LicenceRef-* name
cc: @dgutson

**Comment by sschuberth** [comment] 2023-02-28 21:08
> Here I got that license in the Apprendix, but that license doesn't exist.

I guess that's supposed to say that no license text is displayed. The license / license name does [exist](https://scancode-licensedb.aboutcode.org/mit-nagy.html).

Is ScanCode installed on the machine you run the `report` command on? Because ORT gets the ttexts for ScanCode-specific license names from the ScanCode installation directory.

**Comment by Franco0700** [comment] 2023-02-28 21:16
I'm using docker builded from source code as the getting started guide says....
```

git clone <this_repo>
cd ort
docker build -t ort .

```
I don't know If I must do anything else in the docker image...

**Comment by sschuberth** [comment] 2023-04-21 06:03
@Franco0700 does the problem persist? Can you provide an example project to scan that exposes the issue?

**Comment by sschuberth** [comment] 2024-08-27 08:46
Closing this as a duplicate of https://github.com/oss-review-toolkit/ort/issues/8147.

**Closed by sschuberth** 2024-08-27 08:46 UTC
Labels: reporter, needs info
