### ISSUE TITLE
GradleInspector fails to detect some package metadata attributes with Gradle wrapper 8.2

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#8068] opened 2023-12-27 11:22 UTC
Prior to upgrading [1] to use Gradle wrapper version 8.5 (instead of verison 8.2), the GradleInspector failed
to detected the source artifact URL for most of the dependencies of [1]. In particular, for the Kotlin libraries such
as the Kotlin `stdlib`. 

Note: The analysis also worked with Gradle 8.4.

[1] https://github.com/epam/ai-dial-core

**Comment by fviernau** [comment] 2023-12-27 13:12
> FYI, [gradle/gradle#23208](https://github.com/gradle/gradle/issues/23208) was fixed only in Gradle 8.5, maybe it's related.

It worked also with Gradle 8.4, I've updated the description accordingly.

**Comment by sschuberth** [comment] 2024-03-15 14:30
> Prior to upgrading [1] to use Gradle wrapper version 8.5

Note to myself: SO the version to analyze would be https://github.com/epam/ai-dial-core/commit/a5d603e334446ca7d4a615a69321597d6a67ef8b, which is the parent of https://github.com/epam/ai-dial-core/commit/ff84dd90e8c216f7cf30859cc9d5541eaaa7d7cf.

**Comment by sschuberth** [comment] 2024-03-15 16:33
The issue is caused by a regression in Gradle 8.2 that was fixed in Gradle 8.2.1 via https://github.com/gradle/gradle/pull/25675.

**Closed** 2024-03-15 18:30 UTC
Labels: bug, analyzer
