### ISSUE TITLE
License in package.json

### ISSUE THREAD

**Issue by dgutson** [oss-review-toolkit/ort#6752] opened 2023-03-28 00:58 UTC
There are cases where the license is in the package.json file, for example: https://github.com/component/indexof . At least this doesn't show up in the licenseDeclared of the SPDX output.

**Comment by sschuberth** [comment] 2023-03-28 08:50
I can't reproduce this as I just ran an analysis and it yielded:

```
---
SPDXID: "SPDXRef-DOCUMENT"
spdxVersion: "SPDX-2.2"
creationInfo:
  created: "2023-03-28T08:46:25Z"
  creators:
  - "Tool: OSS Review Toolkit - DOCKER-SNAPSHOT"
  licenseListVersion: "3.20"
name: "Unnamed document"
dataLicense: "CC0-1.0"
documentNamespace: "spdx://436ababa-c58d-4e0d-aa30-c5d3a6281d7b"
documentDescribes:
- "SPDXRef-Project-NPM-component-indexof-0.0.3"
packages:
- SPDXID: "SPDXRef-Project-NPM-component-indexof-0.0.3"
  copyrightText: "Copyright (c) 2011 TJ Holowaychuk <tj@vision-media.ca>\nCopyright\
    \ (c) 2012 TJ Holowaychuk"
  downloadLocation: "NONE"
  filesAnalyzed: false
  homepage: "NONE"
  licenseConcluded: "NOASSERTION"
  licenseDeclared: "MIT"
  name: "component-indexof"
  summary: "NONE"
  versionInfo: "0.0.3"
```

If you analyzed this package directly, did you maybe forget to enabled `allowDynamicVersions` (and ignored the respective error in the analyzer result)?

**Comment by sschuberth** [comment] 2023-03-28 09:10
As a side note, https://github.com/component/indexof/blob/master/package.json is awkward as it contains the `license` key twice ([here](https://github.com/component/indexof/blob/fde79ca75f89c470dd527d134d88b8719ae4587c/package.json#L5) and [here](https://github.com/component/indexof/blob/fde79ca75f89c470dd527d134d88b8719ae4587c/package.json#L20)), but our JSON parser is able to tolerate that.

**Comment by sschuberth** [comment] 2023-04-21 06:06
> At least this doesn't show up in the licenseDeclared of the SPDX output.

I believe your specific issue has been addressed by https://github.com/oss-review-toolkit/ort/pull/6760.

**Closed by sschuberth** 2023-04-21 06:06 UTC
Labels: analyzer, needs info
