### ISSUE TITLE
ORT, GitLab Pipeline Gradle - DownloadException: Download failed for 'Maven:org.hamcrest:hamcrest-core:1.3'.

### ISSUE THREAD

**Issue by woznik** [oss-review-toolkit/ort#3140] opened 2020-09-28 16:39 UTC
Hello

Recently I struggle with test over ORT scanner for sample Gradle project
When I execute the analyzer, scanner locallyon my linux machine using ORT image I can sucessfully scan the dependancies but when I try to scan the same project from a gitlab pipeline repository over corporate proxy (proxy is provided in http_proxy and https_proxy variables) I obtain following warnings in the analyzer part:

```
16:28:35.287 [Analyzer-1] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Resolving Gradle dependencies for '/builds/opensource/oss-compliance-sample-projects/gradle-01/build.gradle'...
Downloading https://services.gradle.org/distributions/gradle-6.6.1-bin.zip
.................................................................................................
16:28:59.696 [Analyzer-1] WARN  org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Unable to find 'joda-time:joda-time:jar:2.2' in any of [https://repo.maven.apache.org/maven2, https://repo.maven.apache.org/maven2/].
16:29:00.015 [Analyzer-1] WARN  org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Unable to find 'joda-time:joda-time:jar:sources:2.2' in any of [https://repo.maven.apache.org/maven2, https://repo.maven.apache.org/maven2/].
16:29:00.821 [Analyzer-1] WARN  org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Unable to find 'junit:junit:jar:4.12' in any of [https://repo.maven.apache.org/maven2, https://repo.maven.apache.org/maven2/].
16:29:00.834 [Analyzer-1] WARN  org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Unable to find 'junit:junit:jar:sources:4.12' in any of [https://repo.maven.apache.org/maven2, https://repo.maven.apache.org/maven2/].
16:29:00.868 [Analyzer-1] WARN  org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Unable to find 'org.hamcrest:hamcrest-core:jar:1.3' in any of [https://repo.maven.apache.org/maven2, https://repo.maven.apache.org/maven2/].
16:29:00.878 [Analyzer-1] WARN  org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Unable to find 'org.hamcrest:hamcrest-core:jar:sources:1.3' in any of [https://repo.maven.apache.org/maven2, https://repo.maven.apache.org/maven2/].
16:29:08.465 [FileStoreAttributeReader-2] WARN  org.eclipse.jgit.util.FS - locking FileBasedConfig[/root/.config/jgit/config] failed after 5 retries
16:29:08.493 [Analyzer-1] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Resolving Gradle dependencies for 'build.gradle' took 33.199490799s.
Found 1 project(s) in total.
Writing analyzer result to '/builds/opensource/oss-compliance-sample-projects/gradle-01/ort/analyzer/analyzer-result.yml'.
```
scanner part with an ERROR at the end which fails the process:

```
16:31:11.249 [ScanCode-1] INFO  org.ossreviewtoolkit.downloader.Downloader - Trying to download source artifact for 'Maven:org.hamcrest:hamcrest-core:1.3' from ...
16:31:11.250 [ScanCode-1] ERROR org.ossreviewtoolkit.scanner.LocalScanner - Could not download 'Maven:org.hamcrest:hamcrest-core:1.3': DownloadException: Download failed for 'Maven:org.hamcrest:hamcrest-core:1.3'.
Suppressed: DownloadException: Unable to determine a revision to checkout.
```

Do you have any idea if this can be a proxy issue?
If yes how could I pass the proxy settings?

PS: the same pipeline works ok for reular maven and nodejs projects

**Comment by sschuberth** [comment] 2020-09-28 16:48
Which commit of ORT are you using? Please ensure it includes https://github.com/oss-review-toolkit/ort/pull/2909.

**Comment by tsteenbe** [comment] 2020-09-29 07:49
"Unable to determine a revision to checkout" DownloadException  isthrown by ORT if the tool can clone the repository but is unable to find a tag for package version. Looking at https://github.com/hamcrest/JavaHamcrest/tags there are multiple tags with 1.3 in the name whihc may be the issues adding a curation.

You can easily test this by adding a VCS revision curation to your curations.yml 

```
- id: "Maven:org.hamcrest:hamcrest-core:1.3"
    vcs:
      revision: "hamcrest-java-1.3"
```

**Comment by sschuberth** [comment] 2020-09-29 08:03
ORT should be able to determine the correct version tag for `hamcrest-core` without a curation; that's part of my standard test to scan https://github.com/vdurmont/semver4j.git.

**Comment by woznik** [comment] 2020-09-29 16:29
Hello Sebastian
I have used the most recent docker build on the master branch (an hour ago) and sadly there are still  warnings in downloading the artifacts in Analyzer section:
```
15:19:00.679 [Analyzer-1] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Resolving Gradle dependencies for '/builds/opensource/oss-compliance-sample-projects/gradle-01/build.gradle'...
Downloading https://services.gradle.org/distributions/gradle-6.6.1-bin.zip
.................................................................................................
15:19:28.660 [Analyzer-1] WARN  org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Unable to find 'joda-time:joda-time:jar:2.2' in any of [https://repo.maven.apache.org/maven2, https://repo.maven.apache.org/maven2/].
15:19:29.352 [Analyzer-1] WARN  org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Unable to find 'joda-time:joda-time:jar:sources:2.2' in any of [https://repo.maven.apache.org/maven2, https://repo.maven.apache.org/maven2/].
15:19:30.611 [Analyzer-1] WARN  org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Unable to find 'junit:junit:jar:4.12' in any of [https://repo.maven.apache.org/maven2, https://repo.maven.apache.org/maven2/].
15:19:30.645 [Analyzer-1] WARN  org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Unable to find 'junit:junit:jar:sources:4.12' in any of [https://repo.maven.apache.org/maven2, https://repo.maven.apache.org/maven2/].
15:19:30.750 [Analyzer-1] WARN  org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Unable to find 'org.hamcrest:hamcrest-core:jar:1.3' in any of [https://repo.maven.apache.org/maven2, https://repo.maven.apache.org/maven2/].
15:19:30.771 [Analyzer-1] WARN  org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Unable to find 'org.hamcrest:hamcrest-core:jar:sources:1.3' in any of [https://repo.maven.apache.org/maven2, https://repo.maven.apache.org/maven2/].
15:19:34.606 [Analyzer-1] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Resolving Gradle dependencies for 'build.gradle' took 33.92265976s.
Found 1 project(s) in total.
Writing analyzer result to '/builds/opensource/oss-compliance-sample-projects/gradle-01/ort/analyzer/analyzer-result.yml'.
```

and then in Scanner section:

15:34:33.108 [ScanCode-1] INFO  org.ossreviewtoolkit.downloader.Downloader - Trying to download source artifact for 'Maven:joda-time:joda-time:2.2' from ...
15:34:33.109 [ScanCode-1] ERROR org.ossreviewtoolkit.scanner.LocalScanner - Could not download 'Maven:joda-time:joda-time:2.2': DownloadException: Download failed for 'Maven:joda-time:joda-time:2.2'.
Suppressed: DownloadException: Unable to determine a revision to checkout.
Suppressed: DownloadException: No source artifact URL provided for 'Maven:joda-time:joda-time:2.2'.

15:36:13.152 [ScanCode-1] INFO  org.ossreviewtoolkit.downloader.Downloader - Trying to download source artifact for 'Maven:org.hamcrest:hamcrest-core:1.3' from ...
15:36:13.152 [ScanCode-1] ERROR org.ossreviewtoolkit.scanner.LocalScanner - Could not download 'Maven:org.hamcrest:hamcrest-core:1.3': DownloadException: Download failed for 'Maven:org.hamcrest:hamcrest-core:1.3'.
Suppressed: DownloadException: Unable to determine a revision to checkout.
Suppressed: DownloadException: No source artifact URL provided for 'Maven:org.hamcrest:hamcrest-core:1.3'.
15:36:13.153 [ScanCode-1] INFO  kotlinx.coroutines.CoroutineScope - Finished scanning Maven:org.hamcrest:hamcrest-core:1.3 in thread 'ScanCode-1' (4/4).
```

**Comment by sschuberth** [comment] 2020-09-30 09:19
I'm sorry @woznik, but I'm clueless. I have a very similar setup using the Jenkinsfile / Dockerfile behind a proxy, and e.g. for the https://github.com/vdurmont/semver4j.git project hamcrest-core and other dependencies are downloaded just fine.

Also note that the logged warnings actually come directly from the Maven resolver library, not ORT itself. So it seems something is really wrong with your Maven Central access. Is there maybe some proxy magic going on, like rerouting Maven Central requests to JCenter, which is actually something I've seen Travis CI doing in the past?

*Edit:* But something very suspicious is going on in your logs anyway. Note how e.g. in

    Unable to find 'org.hamcrest:hamcrest-core:jar:1.3' in any of [https://repo.maven.apache.org/maven2, https://repo.maven.apache.org/maven2/].

the URL "https://repo.maven.apache.org/maven2" is listed twice, which is something that has been addressed quite some time ago in https://github.com/oss-review-toolkit/ort/pull/361. So please triple-check that you are actually using a current build of ORT.

**Comment by woznik** [comment] 2020-09-30 15:53
Yes. I use the the latest sources to build the image (ScanCode 3.2.1rc2)
![image](https://user-images.githubusercontent.com/17202024/94707435-b50aad00-0343-11eb-8058-57d346e8d1c6.png)
Now I forked the project that you mentioned https://github.com/vdurmont/semver4j.git to my Corporate Gitlab Community edition and it works well with ORT. I have no problem in Maven projects
The case is with Gradle 
Can you do a test on your side with a following project:
https://github.com/Ziggomatica/gradle-hello-world
?
because I have still issues in transfering the proxy issues in my opinion

```
Downloading https://services.gradle.org/distributions/gradle-6.6.1-bin.zip
.................................................................................................
15:49:35.453 [Analyzer-1] ERROR org.ossreviewtoolkit.analyzer.PackageManager - Resolving dependencies for 'build.gradle' failed with: BuildException: Could not fetch model of type 'DependencyTreeModel' using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-6.6.1-bin.zip'.
Caused by: LocationAwareException: Build file '/builds/opensource/oss-compliance-sample-projects/gradle-02/build.gradle' line: 8
Plugin [id: 'org.roboscratch.robot', version: '0.1.3'] was not found in any of the following sources:
- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.roboscratch.robot:org.roboscratch.robot.gradle.plugin:0.1.3')
  Searched in the following repositories:
    Gradle Central Plugin Repository
Caused by: UnknownPluginException: Plugin [id: 'org.roboscratch.robot', version: '0.1.3'] was not found in any of the following sources:
- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.roboscratch.robot:org.roboscratch.robot.gradle.plugin:0.1.3')
  Searched in the following repositories:
    Gradle Central Plugin Repository
```

**Comment by sschuberth** [comment] 2020-09-30 18:54
> Can you do a test on your side with a following project:
> https://github.com/Ziggomatica/gradle-hello-world
> ?

I indeed also have issues with that project, but totally different ones than you: That project hasn't seen any updates for 3 years, and it does not use the Gradle wrapper. Which means it will by default use the same (modern) Gradle version that ORT uses, althought it was probably meant to use a much older Gradle version. That results in errors like

    Caused by: GroovyRuntimeException: Cannot set the value of read-only property 'additionalSourceDirs' for task ':jacocoTestReport' of type org.gradle.testing.jacoco.tasks.JacocoReport.

as the Gradle data model probably has changed meanwhile. But I'm not seeing any artifact download related issues like you do.

If the issue only appears with Gradle projects, then it's probably worth checking `~/.gradle/gradle.properties` on the machine that runs ORT (if you mount the HOME into Docker) for any suspicious entries.

**Comment by woznik** [comment] 2020-10-01 14:28
Hi Sebastien
I decided to use a newer project 

https://github.com/gradle/gradle-build-scan-quickstart

which is using gradlew. I placed the gradle properties file in $HOME/.gradle/gradle.properties (then in project root dir) and sadly I have the same messages.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by retrofit2.Platform (file:/opt/ort/lib/retrofit-2.9.0.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
________ _____________________
\_____  \\______   \__    ___/ the OSS Review Toolkit, version 0.1.0-SNAPSHOT.
 /   |   \|       _/ |    |    Running 'analyze' under Java 11.0.8 on Linux with
/    |    \    |   \ |    |    ORT_CONFIG_DIR = /root/.ort/config
\_______  /____|_  / |____|    ORT_DATA_DIR = /root/.ort
        \/       \/
More environment variables:
http_proxy = http://pwozni06:Niebieski9(@126.179.0.206:9090
https_proxy = http://pwozni06:Niebieski9(@126.179.0.206:9090
JAVA_HOME = /opt/java/openjdk
ANDROID_HOME = /opt/android-sdk
GOPATH = /go

The following package managers are activated:
        Bower, Bundler, Cargo, Carthage, Conan, DotNet, GoDep, GoMod, Gradle, Maven, NPM, NuGet, PhpComposer, PIP, Pipenv, Pub, SBT, SpdxDocumentFile, Stack, Yarn
Analyzing project path:
        /project
14:15:13.466 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/.git' as it is hard-coded to be ignored.
14:15:14.835 [main] INFO  org.ossreviewtoolkit.utils.OrtAuthenticator - Authenticator is already installed.
14:15:14.836 [main] INFO  org.ossreviewtoolkit.utils.OrtProxySelector - Proxy selector is already installed.
14:15:14.837 [main] INFO  org.ossreviewtoolkit.analyzer.Analyzer - Gradle projects found in:
14:15:14.838 [main] INFO  org.ossreviewtoolkit.analyzer.Analyzer -      build.gradle
14:15:14.910 [Analyzer-1] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Resolving Gradle dependencies for '/project/build.gradle'...
Downloading https://services.gradle.org/distributions/gradle-6.6-bin.zip
.................................................................................................
14:16:54.533 [Analyzer-1] INFO  org.ossreviewtoolkit.analyzer.managers.utils.HttpsMirrorSelector - HTTP access to central (http://repo1.maven.org/maven2) was disabled. Automatically switching to HTTPS.
14:17:44.643 [Analyzer-1] WARN  org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Unable to find 'com.google.guava:guava:jar:29.0-jre' in any of [https://repo.maven.apache.org/maven2, https://jcenter.bintray.com/].
14:18:25.214 [Analyzer-1] WARN  org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Unable to find 'com.google.guava:guava:jar:sources:29.0-jre' in any of [https://repo.maven.apache.org/maven2, https://jcenter.bintray.com/].
14:19:25.977 [Analyzer-1] WARN  org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Unable to find 'com.google.guava:failureaccess:jar:1.0.1' in any of [https://oss.sonatype.org/content/repositories/snapshots, https://repo.maven.apache.org/maven2, https://jcenter.bintray.com/].
```

normally I can run sucessfully 

```
gradlew build
gradlew dependencies
```

**Comment by sschuberth** [comment] 2020-10-01 14:53
Sorry, I'm clueless. @mnonnenmacher would you have an idea? Can it be that our "automatic upgrade" to HTTPS causes the issue, see

    HTTP access to central (http://repo1.maven.org/maven2) was disabled. Automatically switching to HTTPS.

**Comment by mnonnenmacher** [comment] 2020-10-01 17:07
Sorry, I also have no idea what could cause this, I haven't run ORT behind a proxy so far. @sschuberth Does analyzing https://github.com/gradle/gradle-build-scan-quickstart work for you behind a proxy? At this point I would probably run Wireshark to check if the request are sent to the proxy or directly to the Maven repositories.

**Comment by sschuberth** [comment] 2020-10-01 20:00
> @sschuberth Does analyzing https://github.com/gradle/gradle-build-scan-quickstart work for you behind a proxy?

Yes it does, I just tried, no analyzer issues.

**Comment by woznik** [comment] 2020-10-02 09:39
OK, so it must be a proxy issue
Normally when I run ORT in docker interactive mode I can run successfully gradlew dependencies
But when I run /opt/ort/bin/ort  analyze there are proxy issues. 
Is there any way I could configure more in ORT to test proxy issue?

This problem is wired because during a scan phase ORT downloaded and stored 4 artifacts out of 9

![image](https://user-images.githubusercontent.com/17202024/94909766-f3b77900-04a3-11eb-9a98-e7a33fb0b52b.png)

I need to dig deeper here

**Comment by sschuberth** [comment] 2020-10-02 10:08
Maybe some sort of rate limiting in our proxy?

**Comment by woznik** [comment] 2020-10-02 11:49
I am not sure because simple "./gradlew build" and "./gradlew dependencies" commands on the same machine go well using exactly the same proxy settings. I would rather play with ScanCode to check that routing

**Comment by sschuberth** [comment] 2020-10-21 11:48
@woznik out of curiosity, were you able to resolve this issue?

**Comment by woznik** [comment] 2020-10-21 15:26
Hi
I was about to write
No, I didn't. I couldn't find a way to investigate. 
I deployed docker container, set up gradle.properties in ~/.gradle directory
I made a test and I was able to run gradle build, gradle dependencies but '--info analyze' still produces:

```
[INFO] ORT analyse
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by retrofit2.Platform (file:/opt/ort/lib/retrofit-2.9.0.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
________ _____________________
\_____  \\______   \__    ___/ the OSS Review Toolkit, version 0.1.0-SNAPSHOT.
 /   |   \|       _/ |    |    Running 'analyze' under Java 11.0.8 on Linux with
/    |    \    |   \ |    |    ORT_CONFIG_DIR = /root/.ort/config
\_______  /____|_  / |____|    ORT_DATA_DIR = /root/.ort
        \/       \/
More environment variables:
http_proxy = http://*******************:8080
https_proxy = http://********************:8080
JAVA_HOME = /opt/java/openjdk
ANDROID_HOME = /opt/android-sdk
GOPATH = /go
The following package managers are activated:
	Bower, Bundler, Cargo, Carthage, Conan, DotNet, GoDep, GoMod, Gradle, Maven, NPM, NuGet, PhpComposer, PIP, Pipenv, Pub, SBT, SpdxDocumentFile, Stack, Yarn
Analyzing project path:
	/builds/opensource/oss-compliance-sample-projects/gradle-03
12:58:23.789 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/builds/opensource/oss-compliance-sample-projects/gradle-03/.git' as it is hard-coded to be ignored.
12:58:25.494 [main] INFO  org.ossreviewtoolkit.utils.OrtAuthenticator - Authenticator is already installed.
12:58:25.494 [main] INFO  org.ossreviewtoolkit.utils.OrtProxySelector - Proxy selector is already installed.
12:58:25.496 [main] INFO  org.ossreviewtoolkit.analyzer.Analyzer - Gradle projects found in:
12:58:25.496 [main] INFO  org.ossreviewtoolkit.analyzer.Analyzer - 	build.gradle
12:58:25.585 [Analyzer-1] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Resolving Gradle dependencies for '/builds/opensource/oss-compliance-sample-projects/gradle-03/build.gradle'...
Downloading https://services.gradle.org/distributions/gradle-6.6-bin.zip
.................................................................................................
12:58:57.544 [Analyzer-1] INFO  org.ossreviewtoolkit.analyzer.managers.utils.HttpsMirrorSelector - HTTP access to central (http://repo1.maven.org/maven2) was disabled. Automatically switching to HTTPS.
12:59:02.883 [Analyzer-1] WARN  org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Unable to find 'com.google.guava:guava:jar:29.0-jre' in any of [https://repo.maven.apache.org/maven2, https://jcenter.bintray.com/, https://dl.google.com/dl/android/maven2/, https://maven.google.com, http://repo1.maven.org/maven2].
12:59:03.187 [Analyzer-1] WARN  org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Unable to find 'com.google.guava:guava:jar:sources:29.0-jre' in any of [https://repo.maven.apache.org/maven2, https://jcenter.bintray.com/, https://dl.google.com/dl/android/maven2/, https://maven.google.com, http://repo1.maven.org/maven2].
12:59:03.840 [Analyzer-1] WARN  org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Unable to find 'com.google.guava:failureaccess:jar:1.0.1' in any of [https://oss.sonatype.org/content/repositories/snapshots, https://repo.maven.apache.org/maven2, https://jcenter.bintray.com/, https://dl.google.com/dl/android/maven2/, https://maven.google.com, http://repo1.maven.org/maven2].
```
in the scan section I obtain errors in:

```
13:00:23.905 [ScanCode-1] INFO  kotlinx.coroutines.CoroutineScope - No stored result found for Maven:com.google.code.findbugs:jsr305:3.0.2 and ScannerDetails(name=ScanCode, version=3.2.1-rc2, configuration=--copyright --license --ignore *.ort.yml --info --strip-root --timeout 300 --ignore HERE_NOTICE --ignore META-INF/DEPENDENCIES --json-pp), scanning package in thread 'ScanCode-1' (2/10).
13:00:23.908 [ScanCode-1] INFO  org.ossreviewtoolkit.downloader.Downloader - Trying to download 'Maven:com.google.code.findbugs:jsr305:3.0.2' sources to '/builds/opensource/oss-compliance-sample-projects/gradle-03/ort/scanner/downloads/Maven/com.google.code.findbugs/jsr305/3.0.2' from VCS...
13:00:23.908 [ScanCode-1] INFO  org.ossreviewtoolkit.downloader.Downloader - Using processed VcsInfo(type=Git, url=https://code.google.com/p/jsr-305, revision=, resolvedRevision=null, path=). Original was VcsInfo(type=Git, url=https://code.google.com/p/jsr-305/, revision=, resolvedRevision=null, path=).
13:00:23.909 [ScanCode-1] INFO  org.ossreviewtoolkit.downloader.Downloader - Detected VCS type 'Git' from type name 'Git'.
13:00:23.935 [ScanCode-1] INFO  org.ossreviewtoolkit.utils.ProcessCapture - Running 'git --version' in '/builds/opensource/oss-compliance-sample-projects/gradle-03'...
13:00:24.306 [ScanCode-1] INFO  org.ossreviewtoolkit.downloader.VersionControlSystem - No Git revision for version '3.0.2' found: IOException: Unable to list the remote tags.
Caused by: TransportException: https://code.google.com/p/jsr-305: Redirection blocked: redirect https://code.google.com/p/jsr-305/ -> https://code.google.com/archive/p/jsr-305 not allowed
Caused by: TransportException: https://code.google.com/p/jsr-305: Redirection blocked: redirect https://code.google.com/p/jsr-305/ -> https://code.google.com/archive/p/jsr-305 not allowed
13:00:24.314 [ScanCode-1] INFO  org.ossreviewtoolkit.downloader.Downloader - Trying to download source artifact for 'Maven:com.google.code.findbugs:jsr305:3.0.2' from ...
13:00:24.316 [ScanCode-1] ERROR org.ossreviewtoolkit.scanner.LocalScanner - Could not download 'Maven:com.google.code.findbugs:jsr305:3.0.2': DownloadException: Download failed for 'Maven:com.google.code.findbugs:jsr305:3.0.2'.
Suppressed: DownloadException: Unable to determine a revision to checkout.
Suppressed: DownloadException: No source artifact URL provided for 'Maven:com.google.code.findbugs:jsr305:3.0.2'.
13:00:24.316 [ScanCode-1] INFO  kotlinx.coroutines.CoroutineScope - Finished scanning Maven:com.google.code.findbugs:jsr305:3.0.2 in thread 'ScanCode-1' (2/10).
```

**Comment by sschuberth** [comment] 2020-10-28 20:36
> I deployed docker container, set up gradle.properties in ~/.gradle directory

What exactly do you set up in `gradle.properties`?

**Comment by woznik** [comment] 2020-10-30 14:38
I was using a following entries:

systemProp.http.proxyHost=$host
systemProp.http.proxyPort=$port
systemProp.https.proxyHost=$host
systemProp.https.proxyPort=$port
systemProp.http.nonProxyHosts=$no_proxy
systemProp.https.nonProxyHosts=$no_proxy

But now I do some tests on a Gitlab runner with an access to Internet so no proxy is needed

Despite that fact I cannot successfuly run the scan on the following project:

https://github.com/gradle/gradle-build-scan-quickstart

due to a problem on guava side:

```
20:52:14.167 [ScanCode-1] INFO  org.ossreviewtoolkit.downloader.Downloader - Trying to download 'Maven:com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava' sources to '/builds/opensource/oss-compliance-sample-projects/gradle-03/ort/scanner/downloads/Maven/com.google.guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava' from VCS...
20:52:14.167 [ScanCode-1] INFO  org.ossreviewtoolkit.downloader.Downloader - Using VcsInfo(type=Git, url=https://github.com/google/guava.git, revision=, resolvedRevision=null, path=).
20:52:14.167 [ScanCode-1] INFO  org.ossreviewtoolkit.downloader.Downloader - Detected VCS type 'Git' from type name 'Git'.
20:52:14.175 [ScanCode-1] INFO  org.ossreviewtoolkit.utils.ProcessCapture - Running 'git --version' in '/builds/opensource/oss-compliance-sample-projects/gradle-03'...
20:52:14.723 [ScanCode-1] INFO  org.ossreviewtoolkit.downloader.VersionControlSystem - No Git revision for version '9999.0-empty-to-avoid-conflict-with-guava' found: IOException: No matching tag found for version '9999.0-empty-to-avoid-conflict-with-guava'. Please create a tag whose name contains the version.
20:52:14.724 [ScanCode-1] INFO  org.ossreviewtoolkit.downloader.Downloader - Trying to download source artifact for 'Maven:com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava' from ...
20:52:14.725 [ScanCode-1] ERROR org.ossreviewtoolkit.scanner.LocalScanner - Could not download 'Maven:com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava': DownloadException: Download failed for 'Maven:com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'.
Suppressed: DownloadException: Unable to determine a revision to checkout.
Suppressed: DownloadException: No source artifact URL provided for 'Maven:com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'.
20:52:14.725 [ScanCode-1] INFO  kotlinx.coroutines.CoroutineScope - Finished scanning Maven:com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava in thread 'ScanCode-1' (6/10).
```

I see that the dependency `9999.0-empty-to-avoid-conflict-with-guava` in maven repository

**Comment by sschuberth** [comment] 2020-10-30 14:53
> I see that the dependency `9999.0-empty-to-avoid-conflict-with-guava` in maven repository

Yes, but what you *don't* see is a `-sources.jar` artifact, right? 😉 So there is no published sources artifact *and* no SCM information in the POM, hence the downloader cannot download the source code without further help.

Given that the binary JAR artifact is empty (and that's also what the package description states), I'd simply create a curation for this artifact that sets `is_meta_data_only` to `true`.

Ping @MarcelBochtler, this is also of interest to you

**Comment by woznik** [comment] 2020-10-30 15:42
true.
I will create a curation file

**Comment by sschuberth** [comment] 2021-12-13 08:08
> > @sschuberth Does analyzing https://github.com/gradle/gradle-build-scan-quickstart work for you behind a proxy?
> 
> Yes it does, I just tried, no analyzer issues.

BTW, that probably was due to all dependencies being cached locally already. @mnonnenmacher just fixed a long-standing remaining proxy issue in https://github.com/oss-review-toolkit/ort/pull/4839, so I believe the original issue to be fixed now, too. Feel free to reopen otherwise.

**Closed by sschuberth** 2021-12-13 08:08 UTC
Labels: question, analyzer
