### ISSUE TITLE
ORT `go mod` Analysis failed

### ISSUE THREAD

**Issue by lalitbittu11** [oss-review-toolkit/ort#5253] opened 2022-04-13 09:53 UTC
Hello,

ort analysis fails,  below are the logs -

Analysis failed/not completed. Please click 'Upload' to upload source code package.
________ _____________________
\_____ \\______ \__ ___/ the OSS Review Toolkit, version 0.1.0-SNAPSHOT.
/ | \| _/ | | Running 'analyze' under Java 1.8.0_322 on Linux with
/ | \ | \ | | ORT_CONFIG_DIR = /root/.config
\_______ /____|_ / |____| ORT_DATA_DIR = /root/.ort
\/ \/
More environment variables:
SHELL = /bin/bash
TERM = unknown
http_proxy = http://XX.XX.XX.XX:8080
https_proxy = http://XX.XX.XX.XX:8080

The following package managers are activated:
Bower, Bundler, Cargo, Conan, DotNet, GoDep, GoMod, Gradle, Maven, NPM, NuGet, PhpComposer, PIP, Pipenv, Pub, SBT, SpdxDocumentFile, Stack, Yarn
Analyzing project path:
/opt/project/sourcecode/175220
12:43:13.486 [main] INFO org.ossreviewtoolkit.analyzer.Analyzer - Unmanaged projects found in:
12:43:13.488 [main] INFO org.ossreviewtoolkit.analyzer.Analyzer - .
12:43:13.538 [Analyzer-1] INFO org.ossreviewtoolkit.analyzer.PackageManager - Resolving Unmanaged dependencies for '/opt/project/sourcecode/175220'...
12:43:13.634 [Analyzer-1] INFO org.ossreviewtoolkit.utils.OrtAuthenticator - Authenticator was successfully installed.
12:43:13.634 [Analyzer-1] INFO org.ossreviewtoolkit.utils.OrtProxySelector - Proxy selector is already installed.
12:43:13.812 [Analyzer-1] INFO org.ossreviewtoolkit.utils.OrtAuthenticator - Authenticator was successfully installed.
12:43:17.149 [Analyzer-1] WARN org.ossreviewtoolkit.analyzer.managers.Unmanaged - Analysis of local directory '/opt/project/sourcecode/175220' which is not under version control will produce non-cacheable results as no version for the cache key can be determined.
12:43:17.156 [Analyzer-1] INFO org.ossreviewtoolkit.analyzer.PackageManager - Resolving Unmanaged dependencies for '175220' took 3.613950031s.
Found 1 project(s) in total.
Writing analyzer result to '/opt/project/ort/analyzer/82163/analyzer-result.json'.
12:43:17.393 [JGit-FileStoreAttributeWriter-2] WARN org.eclipse.jgit.util.FS - locking FileBasedConfig[/root/.config/jgit/config] failed after 5 retries

Analysis failed/not completed. Please click 'Upload' to upload the source code package

Kindly help to fix this.

Thanks.

**Comment by sschuberth** [comment] 2022-04-13 10:08
> Analysis failed/not completed. Please click 'Upload' to upload the source code package

Where does this output come from? This is not output from ORT itself, so it seem like you're using some service around ORT.

Also, I'm not seeing an actual error in ORT's log output, just warnings. So I'm not sure why the service you're using concludes that "Analysis failed".

You might be better off contacting the people who operate your service around ORT.

**Comment by godfreysilvester** [comment] 2022-04-13 10:09
Adding more errors from the analyzer results.

"message" : "Resolving dependencies for 'go.mod' failed with: IOException: Running 'go mod vendor -v' in '/opt/project/sourcecode/372817/kubectl-kubernetes-1.23.1' failed with exit code 1:\nk8s.io/kubectl/pkg/util/i18n imports\n\tembed: package embed is not in GOROOT (/usr/local/go/src/embed)\nk8s.io/kubectl/pkg/cmd imports\n\tk8s.io/client-go/rest imports\n\tk8s.io/client-go/plugin/pkg/client/auth/exec imports\n\tio/fs: package io/fs is not in GOROOT (/usr/local/go/src/io/fs)\n",
          "severity" : "ERROR"

**Comment by fviernau** [comment] 2022-06-27 18:22
@godfreysilvester , @lalitbittu11 can you tell which ORT version / revision was used to reproduce this issue?

**Comment by sschuberth** [comment] 2022-07-26 05:54
I'm closing this due to a lack of feedback. However, getting the questions answered is still appreciated so that we eventually can reopen the issue.

**Comment by nnobelis** [comment] 2023-09-07 07:56
Sorry for re-opening this old issue but one of our customer is facing the same error as the original reporter:

```
08:19:42.967 [DefaultDispatcher-worker-2] ERROR org.ossreviewtoolkit.analyzer.PackageManager - GoMod failed to resolve dependencies for path 'receiver/go.mod': IOException: Running 'go list -deps -json=Module -buildvcs=false ./...' in '/temp/receiver' failed with exit code 1:
cmd/root.go:4:2: package commons/logger is not in GOROOT (/opt/go/src/commons/logger) 
```

Running latest version of ORT.

The customer adds:

> I tried to research this error and what I get from [this stackoverflow](https://stackoverflow.com/questions/61845013/package-xxx-is-not-in-goroot-when-building-a-go-project) it seems that only one go.mod file should be used per repository.
We have several go modules in our project, so we are using the standard Go approach for a multi-module workspace with a go.work file in the root and go.mod files in the module directories. For more info see here: https://go.dev/doc/tutorial/workspaces
I am afraid we cannot delete the go.mod files in the subdirectories.

Has anyone an idea how this error can be solved ?

**Comment by nnobelis** [comment] 2023-09-07 09:31
Please close this issue.

I cannot reproduce the error locally and, by looking at the StackOverflow linked discussion, it is absolutely not clear that the error is due to multiple Go modules.

**Closed** 2023-09-07 09:43 UTC
Labels: analyzer, needs info
