### ISSUE TITLE
Allow extending URL prefix replacements for Git

### ISSUE THREAD

**Issue by oheger-bosch** [oss-review-toolkit/ort#8500] opened 2024-04-09 10:45 UTC
The `Git` class currently has a hard-coded configuration for replacing URL prefixes, which is limited to replacing the prefix `git://` by `https://`.

In our environment, there was the need to replace a URL like "git@github.com:" (used as a submodule reference and interpreted as SSH) by the URL "https://github.com/". I assume that such replacements cannot be done by ORT in a generic way, since the prefix to be replaced contains a domain; from my research, I found that Git currently does not support wildcards in its prefix mappings. So, it would be nice if there was a straight-forward way to modify the replacement configuration used by `Git`.

Since version control systems are implemented as plugins, would it make sense to support a similar configuration mechanism as for other types of plugins? Via this mechanism, other hard-coded settings (for instance the history depth) could be made configurable as well.

**Comment by sschuberth** [comment] 2024-04-09 11:08
@oheger-bosch, would you agree that this request can be considered as a duplicate of https://github.com/oss-review-toolkit/ort/issues/6698?

**Comment by oheger-bosch** [comment] 2024-04-09 11:37
@sschuberth, thank you for pointing this out. Yes, there is at least a very strong relation between these issues, the same use cases are addressed. Not sure whether the aspect of making the VCS provider itself configurable is new though; the referenced issue seems to focus more on other strategies.

**Comment by sschuberth** [comment] 2024-04-09 11:50
Let's then track these requests together in #6698 as discuss there.

**Closed by sschuberth** 2024-04-09 11:50 UTC
Labels: duplicate
