### ISSUE TITLE
Clarification request on how to select Android target platform for analyzing

### ISSUE THREAD

**Issue by rbieniek** [oss-review-toolkit/ort#5034] opened 2022-02-10 08:53 UTC
We executed the analyzer step on a larger Android project and ran into issues we believe are related to selecting a target platform.

We would like to understand how to pass the Android target plaform to the executor

Sample output:
```
[Gradle:android-app-platform.service.vehicle:network:](https://github.com/oss-review-toolkit/ort/issues/new#Gradle:android-app-platform.service.vehicle:network:)
2022-02-07T00:25:41.537214Z [ERROR]: Gradle - Unresolved: ModuleVersionResolveException: Could not resolve org.jetbrains.kotlinx:kotlinx-datetime.
Caused by: AmbiguousConfigurationSelectionException: The consumer was configured to find attribute 'org.jetbrains.kotlin.platform.type' with value 'common', attribute 'org.jetbrains.kotlin.localToProject' with value 'local to :api:vehicle'. However we cannot choose between the following variants of org.jetbrains.kotlinx:kotlinx-datetime:0.3.1:
- commonMainMetadataElements
- iosArm32ApiElements-published
- iosArm32MetadataElements-published
- iosArm64ApiElements-published
- iosArm64MetadataElements-published
- iosSimulatorArm64ApiElements-published
- iosSimulatorArm64MetadataElements-published
- iosX64ApiElements-published
- iosX64MetadataElements-published
- jsIrApiElements-published
- jsIrRuntimeElements-published
- jsLegacyApiElements-published
- jsLegacyRuntimeElements-published
- jvmApiElements-published
- jvmRuntimeElements-published
- linuxX64ApiElements-published
- macosArm64ApiElements-published
- macosArm64MetadataElements-published
- macosX64ApiElements-published
- macosX64MetadataElements-published
- metadataApiElements
- mingwX64ApiElements-published
- mingwX64MetadataElements-published
- tvosArm64ApiElements-published
- tvosArm64MetadataElements-published
- tvosSimulatorArm64ApiElements-published
- tvosSimulatorArm64MetadataElements-published
- tvosX64ApiElements-published
- tvosX64MetadataElements-published
- watchosArm32ApiElements-published
- watchosArm32MetadataElements-published
- watchosArm64ApiElements-published
- watchosArm64MetadataElements-published
- watchosSimulatorArm64ApiElements-published
- watchosSimulatorArm64MetadataElements-published
- watchosX64ApiElements-published
- watchosX64MetadataElements-published
- watchosX86ApiElements-published
- watchosX86MetadataElements-published
All of them match the consumer attributes:
- Variant 'commonMainMetadataElements' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'common':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-api' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Variant 'iosArm32ApiElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-api' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'ios_arm32' but the consumer didn't ask for it
- Variant 'iosArm32MetadataElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-metadata' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'ios_arm32' but the consumer didn't ask for it
- Variant 'iosArm64ApiElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-api' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'ios_arm64' but the consumer didn't ask for it
- Variant 'iosArm64MetadataElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-metadata' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'ios_arm64' but the consumer didn't ask for it
- Variant 'iosSimulatorArm64ApiElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-api' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'ios_simulator_arm64' but the consumer didn't ask for it
- Variant 'iosSimulatorArm64MetadataElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-metadata' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'ios_simulator_arm64' but the consumer didn't ask for it
- Variant 'iosX64ApiElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-api' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'ios_x64' but the consumer didn't ask for it
- Variant 'iosX64MetadataElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-metadata' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'ios_x64' but the consumer didn't ask for it
- Variant 'jsIrApiElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'js':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-api' but the consumer didn't ask for it
- Provides org.jetbrains.kotlin.js.compiler 'ir' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Variant 'jsIrRuntimeElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'js':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-runtime' but the consumer didn't ask for it
- Provides org.jetbrains.kotlin.js.compiler 'ir' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Variant 'jsLegacyApiElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'js':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-api' but the consumer didn't ask for it
- Provides org.jetbrains.kotlin.js.compiler 'legacy' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Variant 'jsLegacyRuntimeElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'js':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-runtime' but the consumer didn't ask for it
- Provides org.jetbrains.kotlin.js.compiler 'legacy' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Variant 'jvmApiElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
- Unmatched attributes:
- Provides org.gradle.libraryelements 'jar' but the consumer didn't ask for it
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'java-api' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Variant 'jvmRuntimeElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
- Unmatched attributes:
- Provides org.gradle.libraryelements 'jar' but the consumer didn't ask for it
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Variant 'linuxX64ApiElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides artifactType 'org.jetbrains.kotlin.klib' but the consumer didn't ask for it
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-api' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'linux_x64' but the consumer didn't ask for it
- Variant 'macosArm64ApiElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-api' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'macos_arm64' but the consumer didn't ask for it
- Variant 'macosArm64MetadataElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-metadata' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'macos_arm64' but the consumer didn't ask for it
- Variant 'macosX64ApiElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-api' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'macos_x64' but the consumer didn't ask for it
- Variant 'macosX64MetadataElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-metadata' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'macos_x64' but the consumer didn't ask for it
- Variant 'metadataApiElements' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'common':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-metadata' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Variant 'mingwX64ApiElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides artifactType 'org.jetbrains.kotlin.klib' but the consumer didn't ask for it
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-api' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'mingw_x64' but the consumer didn't ask for it
- Variant 'mingwX64MetadataElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides artifactType 'org.jetbrains.kotlin.klib' but the consumer didn't ask for it
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-metadata' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'mingw_x64' but the consumer didn't ask for it
- Variant 'tvosArm64ApiElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-api' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'tvos_arm64' but the consumer didn't ask for it
- Variant 'tvosArm64MetadataElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-metadata' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'tvos_arm64' but the consumer didn't ask for it
- Variant 'tvosSimulatorArm64ApiElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-api' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'tvos_simulator_arm64' but the consumer didn't ask for it
- Variant 'tvosSimulatorArm64MetadataElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-metadata' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'tvos_simulator_arm64' but the consumer didn't ask for it
- Variant 'tvosX64ApiElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-api' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'tvos_x64' but the consumer didn't ask for it
- Variant 'tvosX64MetadataElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-metadata' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'tvos_x64' but the consumer didn't ask for it
- Variant 'watchosArm32ApiElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-api' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'watchos_arm32' but the consumer didn't ask for it
- Variant 'watchosArm32MetadataElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-metadata' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'watchos_arm32' but the consumer didn't ask for it
- Variant 'watchosArm64ApiElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-api' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'watchos_arm64' but the consumer didn't ask for it
- Variant 'watchosArm64MetadataElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-metadata' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'watchos_arm64' but the consumer didn't ask for it
- Variant 'watchosSimulatorArm64ApiElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-api' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'watchos_simulator_arm64' but the consumer didn't ask for it
- Variant 'watchosSimulatorArm64MetadataElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-metadata' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'watchos_simulator_arm64' but the consumer didn't ask for it
- Variant 'watchosX64ApiElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-api' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'watchos_x64' but the consumer didn't ask for it
- Variant 'watchosX64MetadataElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-metadata' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'watchos_x64' but the consumer didn't ask for it
- Variant 'watchosX86ApiElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-api' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'watchos_x86' but the consumer didn't ask for it
- Variant 'watchosX86MetadataElements-published' capability org.jetbrains.kotlinx:kotlinx-datetime:0.3.1 declares attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
- Unmatched attributes:
- Provides org.gradle.status 'release' but the consumer didn't ask for it
- Provides org.gradle.usage 'kotlin-metadata' but the consumer didn't ask for it
- Doesn't say anything about org.jetbrains.kotlin.localToProject (required 'local to :api:vehicle')
- Provides org.jetbrains.kotlin.native.target 'watchos_x86' but the consumer didn't ask for it
```

**Comment by sschuberth** [comment] 2022-02-10 09:18
Closing this as a duplicate of https://github.com/oss-review-toolkit/ort/issues/4694. Explicit selection of the Android configuration / variant is currently not support (but had been briefly discussed in the context of https://github.com/oss-review-toolkit/ort/issues/1774). Pinging @mnonnenmacher FYI.

**Closed by sschuberth** 2022-02-10 09:18 UTC
