### ISSUE TITLE
Could not scan deps with @ on Windows

### ISSUE THREAD

**Issue by fb33** [oss-review-toolkit/ort#2090] opened 2020-01-07 09:46 UTC
Hello

I build ORT locally from the master branch
I run ORT on windows with git bash in admin mode.

The project analyzed is a node project.
(Note, the fix for non-existing github repo works fine, no extra curation needed)

After the scanner phase, I've got 205 errors like :
```
            source: "ScanCode"
            message: "Could not scan 'NPM:@xtuc:long:4.2.2' (1618/1618): ScanException:\
              \ Running 'D:\\Users\\j.dupont\\AppData\\Local\\Temp\\ort1566383016769617362ScanCode-3.0.2\\\
              scancode-toolkit-3.0.2\\scancode.bat --copyright --license --ignore\
              \ *.ort.yml --info --strip-root --timeout 300 --ignore HERE_NOTICE --ignore\
              \ META-INF/DEPENDENCIES --processes 7 --license-diag --verbose C:\\\
              workspace\\POCs\\MOB_ORT\\my-gateway-web\\client-reports\\downloads\\\
              NPM\\%40xtuc\\long\\4.2.2 --json-pp C:\\workspace\\POCs\\MOB_ORT\\my-gateway-web\\\
              client-reports\\native-scan-results\\NPM\\%40xtuc\\long\\4.2.2\\scan-results_ScanCode.json'\
              \ in 'C:\\workspace\\POCs\\MOB_ORT\\oss-review-toolkit' failed with\
              \ exit code 2:\nUsage: scancode [OPTIONS] <input> <OUTPUT FORMAT\n\n\
              \                OPTION(s)>\n\nTry 'scancode --help' for help on options\
              \ and arguments.\n\n\n\nError: Invalid value for \"input\": Path \"\
              C:\\workspace\\POCs\\MOB_ORT\\my-gateway-web\\client-reports\\\
              downloads\\NPM\\0xtuc\\long\\4.2.2\" does not exist.\n\n"
            severity: "ERROR"
```

It seems to be a problem of encode/decode url.
The directory that is searched is C:\workspace\POCs\MOB_ORT\my-gateway-web\client-reports\downloads\NPM\0xtuc\long\4.2.2\
But the directory that was created in windows file system is C:\workspace\POCs\MOB_ORT\my-gateway-web\client-reports\downloads\NPM\%40xtuc\long\4.2.2\

Regards

**Comment by sschuberth** [comment] 2020-01-07 10:14
I'll try to reproduce the issue by scanning https://github.com/EricMCornelius/ease/ which depends on https://www.npmjs.com/package/@xtuc/long.

**Comment by sschuberth** [comment] 2020-01-07 11:41
At least on Linux I cannot reproduce the issue with the attached [analyzer result file](https://github.com/heremaps/oss-review-toolkit/files/4030410/analyzer-result.zip). Can you reproduce the issue on Windows with this file, @fb33?

?

**Comment by sschuberth** [comment] 2020-01-07 12:49
Possibly related ScanCode issues: https://github.com/nexB/scancode-toolkit/issues/442, https://github.com/nexB/scancode-toolkit/issues/542

**Comment by fb33** [comment] 2020-01-07 21:25
Hi, I reproduce the issue with your file, here's the [scan-result](https://github.com/heremaps/oss-review-toolkit/files/4032513/scan-result.zip)

**Comment by sschuberth** [comment] 2020-01-09 08:32
I'm working on Windows today, and there I can indeed reproduce the issue. However, it seems to be a pure ScanCode issue, as I can also reproduce it when calling ScanCode directly:

```
$ scancode --json-pp - --license "NPM\%40xtuc\long\4.2.2\package.json"
Usage: scancode [OPTIONS] <input> <OUTPUT FORMAT OPTION(s)>
Try 'scancode --help' for help on options and arguments.

Error: Invalid value for "input": Path "NPM\0xtuc\long\4.2.2\package.json" does not exist.
```

I've reported it upstream at https://github.com/nexB/scancode-toolkit/issues/1876.

**Comment by Duncan-Howe** [comment] 2020-11-01 01:08
Hopefully this PR will resolve this issue: https://github.com/nexB/scancode-toolkit/pull/2310
It seems to have successfully scanned my Angular application and other NPM modules with scopes beginning with @ from ORT

**Comment by sschuberth** [comment] 2021-11-03 08:33
I'm closing this in favor of the [ScanCode version configuration / upgrade epic](https://github.com/oss-review-toolkit/ort/issues/4631).

**Closed by sschuberth** 2021-11-03 08:33 UTC
Labels: bug, scanner
