### ISSUE TITLE
Fails in monorepo with multiple package.json files with same deps

### ISSUE THREAD

**Issue by elnygren** [oss-review-toolkit/ort#8365] opened 2024-02-29 15:04 UTC
## The setup

* project has sub-projects in sub-dir
* each sub-project has their own package.json
* some NPM packages are installed in many subprojects

## The error
```
Exception in thread "main" java.lang.IllegalArgumentException: Unable to create the AnalyzerResult as it contains packages and projects with the same ids
```

## The "solution"

```
analyzer:
  skip_excluded: true
excludes:
  paths:
  - pattern: "<dir-with-sub-projects>/**"
    reason: "BUILD_TOOL_OF"
    comment : "...Ort blows up without this exclude..."
```

How can I make ort understand that it's OK to have duplicate deps in the package.json files ? 🤔

**Comment by sschuberth** [comment] 2024-02-29 15:55
Let's close this as a duplicate of https://github.com/oss-review-toolkit/ort/issues/6465 to keep the related discussions in a single place.

Unfortunately, there's no definite solution yet. I was proposing something in https://github.com/oss-review-toolkit/ort/pull/6533, but never came around to finish it.

**Closed** 2024-02-29 15:56 UTC
Labels: duplicate, analyzer

**Comment by sschuberth** [comment] 2024-02-29 15:58
> * some NPM packages are installed in many subprojects

BTW, the actual problem is not strictly that the same dependencies are used in multiple projects, but that some of these dependencies are built by projects in the same monorepo.

**Comment by heliocastro** [comment] 2024-03-01 07:36
Can't something like this could hold: 
- Detect ahead packages, marking as provided/dependency ( Something like maven projects do as example )
- Add a configuration to choose over prefer "provided"/"dependency", pushing provided as default
- Ignore the others and add the one as uniq dependency.

Now, i'm correcting myself on he previous sentence, because even been possible to do above, unlike Maven projects that enforce you use the pointed dependency, in this mono repo case the situation happens to be that the internal built version could be modified to a extension that is intended to be used by one subproject, but not the others, though making then different packages, even based on same version.

I consider that this case cause a huge violation pre part of compliance detection, as we can't tell he correct one, thich in the end, failing on Ort side is correct. Someone did it wrong and should be tagged the different internal code as a variant version.

BUT, if both external an the provided code match same code, it will simply matter to use the beginning of thi answer, we allow the configuration decide which one we will be using, ignore the the other, and one version only will appears once.
