### ISSUE TITLE
C# project references are handled like package references

### ISSUE THREAD

**Issue by georg-eckert-zeiss** [oss-review-toolkit/ort#8929] opened 2024-07-22 13:39 UTC
### Describe the bug

C# solutions c may consist of a `*.sln` file and multiple `*.csproj` files which again might reference each other. 

A `*.csproj` file may reference NuGet packages with `<PackageReference...` tags and other projects with `<ProjectReference...` tags.

When analyzing with ORT I get lots of warnings about missing remote metadata for package IDs which actually belong to my own internal project references instead of external packages.

### To Reproduce

1. Create a C# solution
2. Create two projects inside `A` and `XBABB` (this is necessary since a nuget.org package "B" actually exists)
3. reference project `XBABB` from project `A`
4. run the analyzer
5. create a report
6. see the warning
7. 
(or simply use the attached minimal example)

`Fetching package metadata for: XBABB.1.0.0
No package metadata found for XBABB.1.0.0.
        Failed to get remote metadata for name: 'XBABB' version: '1.0.0'. `

### Expected behavior

Project references are not listed as FOSS components.

### Console / log output

```
ort --info analyze -i ~/MyProject/ -f JSON -o ~/ort-test-results/
<truncated>
______________________________                                                     
/        \_______   \__    ___/ The OSS Review Toolkit, version 26.0.0,             
|    |   | |       _/ |    |    built with JDK 11.0.23+9, running under Java 21.0.3.
|    |   | |    |   \ |    |    Executing 'analyze' as 'myuser' on Linux             
\________/ |____|___/ |____|    with 4 CPUs and a maximum of 3996 MiB of memory.    

Environment variables:                                                             
ORT_CONFIG_DIR = /home/myuser/.ort/config                                           
ORT_DATA_DIR = /home/myuser/.ort                                                    
HOME = /home/myuser
SHELL = /bin/bash                                                                  
TERM = xterm-256color                                                              

Looking for ORT configuration in the following file:
        /home/myuser/.ort/config/config.yml

Looking for analyzer-specific configuration in the following files and directories:
        /home/myuser/MyProject/.ort.yml (does not exist)
        /home/myuser/.ort/config/resolutions.yml (does not exist)
The following 1 package manager(s) are enabled:
        NuGet
The following 3 package curation provider(s) are enabled:
        RepositoryConfiguration, DefaultDir, DefaultFile
Analyzing project path:
        /home/myuser/MyProject
Found 2 NuGet definition file(s) at:
        XBABB/XBABB.csproj
        A/A.csproj
Found in total 2 definition file(s) from the following 1 package manager(s):
        NuGet
13:27:32.063 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManagerRunner - Starting NuGet analysis.
13:27:32.069 [DefaultDispatcher-worker-1] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Using NuGet to resolve dependencies for path 'XBABB/XBABB.csproj'...
13:27:32.084 [DefaultDispatcher-worker-1] INFO  org.ossreviewtoolkit.utils.common.ProcessCapture - Running 'nuget-inspector --with-details --verbose --project-file /home/myuser/MyProject/XBABB/XBABB.csproj --json /tmp/ort-NuGetInspector13801298568216150985/nuget-inspector436645026580039057.json' in '/home/myuser/MyProject/XBABB'...
13:27:32.922 [DefaultDispatcher-worker-1] INFO  org.ossreviewtoolkit.utils.ort.OrtProxySelector - Proxy selector was successfully installed.
13:27:32.940 [DefaultDispatcher-worker-1] INFO  org.ossreviewtoolkit.utils.ort.OrtAuthenticator - Authenticator was successfully installed.
13:27:33.186 [DefaultDispatcher-worker-1] INFO  org.ossreviewtoolkit.utils.common.ProcessCapture - Running 'hg root' in '/home/myuser/MyProject/XBABB'...
13:27:33.539 [DefaultDispatcher-worker-1] INFO  org.ossreviewtoolkit.analyzer.PackageManager - NuGet resolved dependencies for path 'XBABB/XBABB.csproj' in 1.459525802s.
13:27:33.539 [DefaultDispatcher-worker-1] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Using NuGet to resolve dependencies for path 'A/A.csproj'...
13:27:33.547 [DefaultDispatcher-worker-1] INFO  org.ossreviewtoolkit.utils.common.ProcessCapture - Running 'nuget-inspector --with-details --verbose --project-file /home/myuser/MyProject/A/A.csproj --json /tmp/ort-NuGetInspector5821953169302856016/nuget-inspector4045707755313343774.json' in '/home/myuser/MyProject/A'...
13:27:34.855 [DefaultDispatcher-worker-1] INFO  org.ossreviewtoolkit.utils.common.ProcessCapture - Running 'hg root' in '/home/myuser/MyProject/A'...
13:27:35.004 [DefaultDispatcher-worker-1] INFO  org.ossreviewtoolkit.analyzer.PackageManager - NuGet resolved dependencies for path 'A/A.csproj' in 1.464909396s.
13:27:35.006 [DefaultDispatcher-worker-1] INFO  kotlinx.coroutines.CoroutineScope - Finished NuGet analysis.
13:27:35.032 [main] INFO  org.ossreviewtoolkit.utils.common.ProcessCapture - Running 'hg root' in '/home/myuser/MyProject'...
13:27:35.219 [main] INFO  org.ossreviewtoolkit.model.utils.ConfigurationResolver - Getting 0 package curation(s) from provider 'RepositoryConfiguration' took 394.007us.
13:27:35.219 [main] INFO  org.ossreviewtoolkit.model.utils.ConfigurationResolver - Getting 0 package curation(s) from provider 'DefaultDir' took 5.4us.
13:27:35.220 [main] INFO  org.ossreviewtoolkit.model.utils.ConfigurationResolver - Getting 0 package curation(s) from provider 'DefaultFile' took 2.6us.
Wrote analyzer result to '/home/myuser/ort-test-results/analyzer-result.json' (0.00 MiB) in 1.008807826s.
The analysis took 3.231642366s.
Found 2 project(s) and 1 package(s) in total (not counting excluded ones).
Applied 0 curation(s) from 0 of 3 provider(s).
Resolved issues: 0 errors, 0 warnings, 0 hints.
Unresolved issues: 0 errors, 1 warning, 0 hints.
There is 1 unresolved issue with a severity equal to or greater than the WARNING threshold.
 
<truncated>
```

Leaving us with the following result:

```json
{
  "repository" : {
    "vcs" : {
      "type" : "",
      "url" : "",
      "revision" : "",
      "path" : ""
    },
    "vcs_processed" : {
      "type" : "",
      "url" : "",
      "revision" : "",
      "path" : ""
    },
    "config" : { }
  },
  "analyzer" : {
    "start_time" : "2024-07-22T13:27:31.971079030Z",
    "end_time" : "2024-07-22T13:27:35.202721396Z",
    "environment" : {
      "ort_version" : "26.0.0",
      "build_jdk" : "11.0.23+9",
      "java_version" : "21.0.3",
      "os" : "Linux",
      "processors" : 4,
      "max_memory" : 4190109696,
      "variables" : {
        "HOME" : "/home/myuser",
        "SHELL" : "/bin/bash",
        "TERM" : "xterm-256color"
      },
      "tool_versions" : { }
    },
    "config" : {
      "allow_dynamic_versions" : false,
      "enabled_package_managers" : [ "Nuget", "NPM" ],
      "skip_excluded" : true
    },
    "result" : {
      "projects" : [ {
        "id" : "NuGet::A/A.csproj:",
        "definition_file_path" : "",
        "declared_licenses" : [ ],
        "declared_licenses_processed" : { },
        "vcs" : {
          "type" : "",
          "url" : "",
          "revision" : "",
          "path" : ""
        },
        "vcs_processed" : {
          "type" : "",
          "url" : "",
          "revision" : "",
          "path" : ""
        },
        "homepage_url" : "",
        "scope_names" : [ "net8.0" ]
      }, {
        "id" : "NuGet::XBABB/XBABB.csproj:",
        "definition_file_path" : "",
        "declared_licenses" : [ ],
        "declared_licenses_processed" : { },
        "vcs" : {
          "type" : "",
          "url" : "",
          "revision" : "",
          "path" : ""
        },
        "vcs_processed" : {
          "type" : "",
          "url" : "",
          "revision" : "",
          "path" : ""
        },
        "homepage_url" : "",
        "scope_names" : [ "net8.0" ]
      } ],
      "packages" : [ {
        "id" : "NuGet::XBABB:1.0.0",
        "purl" : "pkg:nuget/XBABB@1.0.0",
        "declared_licenses" : [ ],
        "declared_licenses_processed" : { },
        "description" : "",
        "homepage_url" : "",
        "binary_artifact" : {
          "url" : "",
          "hash" : {
            "value" : "",
            "algorithm" : ""
          }
        },
        "source_artifact" : {
          "url" : "",
          "hash" : {
            "value" : "",
            "algorithm" : ""
          }
        },
        "vcs" : {
          "type" : "",
          "url" : "",
          "revision" : "",
          "path" : ""
        },
        "vcs_processed" : {
          "type" : "",
          "url" : "",
          "revision" : "",
          "path" : ""
        }
      } ],
      "dependency_graphs" : {
        "NuGet" : {
          "packages" : [ "NuGet::XBABB:1.0.0" ],
          "scopes" : {
            ":A/A.csproj::net8.0" : [ {
              "root" : 0
            } ]
          },
          "nodes" : [ {
            "issues" : [ {
              "timestamp" : "2024-07-22T13:27:34.845943262Z",
              "source" : "NuGet",
              "message" : "Failed to get remote metadata for name: 'XBABB' version: '1.0.0'. System.Exception: No package metadata found for XBABB.1.0.0.",
              "severity" : "WARNING"
            } ]
          } ],
          "edges" : [ ]
        }
      }
    }
  },
  "scanner" : null,
  "advisor" : null,
  "evaluator" : null,
  "resolved_configuration" : {
    "package_curations" : [ {
      "provider" : {
        "id" : "RepositoryConfiguration"
      },
      "curations" : [ ]
    }, {
      "provider" : {
        "id" : "DefaultDir"
      },
      "curations" : [ ]
    }, {
      "provider" : {
        "id" : "DefaultFile"
      },
      "curations" : [ ]
    } ]
  }
}
```

### Environment

* ORT version: 26.0.0
* Java version: 21-openjre
* OS: Ubuntu 22.04

[MyProject.zip](https://github.com/user-attachments/files/16334305/MyProject.zip)

**Comment by sschuberth** [comment] 2024-08-13 12:25
Thanks for the report @georg-eckert-zeiss. I see that by now you have filed https://github.com/nexB/nuget-inspector/issues/54 in the upstream *nuget-inspector* project, which is what I would have proposed. Let's close this here as the problem is indeed an upstream issue.

**Closed by sschuberth** 2024-08-13 12:25 UTC
Labels: bug, analyzer
