### ISSUE TITLE
Ort.jar is not present after build

### ISSUE THREAD

**Issue by AnishaM7** [oss-review-toolkit/ort#6512] opened 2023-02-17 17:50 UTC
we are using ` ./gradlew --no-daemon --stacktrace cli:installDist` build ort, ort build is successful, 
![image](https://user-images.githubusercontent.com/62882541/219733911-6f27c36b-8f3b-4ae6-b673-3c1da81374a6.png)
but we are not getting the ort.jar file in the build output in `ls -al cli/build/install/ort/lib/` folder ( we see several other jar)

Please let us know when can we find the same

**Comment by sschuberth** [comment] 2023-02-17 18:52
There is no single (fat) JAR for ORT anymore as of https://github.com/oss-review-toolkit/ort/pull/6322. Instead, the whole directory at `./cli/build/install/ort` contains the ORT distribution, and you can run ORT like `./cli/build/install/ort/bin/ort --help`. If you want to bundle the ORT distribution (e.g. in order to install it on another machine), use the `:cli:distTar` or `:cli:distZip` task to create an archive containing the distribution.

**Comment by sschuberth** [comment] 2023-02-20 15:18
Meanwhile also https://github.com/oss-review-toolkit/ort/pull/6514 has been merged, which should address the confusion.

**Closed by sschuberth** 2023-02-20 15:18 UTC
Labels: question, build

**Comment by AnishaM7** [comment] 2023-02-21 09:04
Hi, Could please let us know where the archive will be generated, cli:distTar  (in which folder zip file is present )

**Comment by sschuberth** [comment] 2023-02-21 09:15
> Could please let us know where the archive will be generated,

It's being generated at `cli/build/distributions/ort-<sha1>.tar`, where `<sha1>` is a placeholder for the Git revision from which the distribution was built.

**Comment by AnishaM7** [comment] 2023-02-22 10:44
Hi @sschuberth,can you pls let me know how can we use this build result  and do ort scan

**Comment by sschuberth** [comment] 2023-02-22 11:41
@AnishaM7 it's described in the README: https://github.com/oss-review-toolkit/ort#basic-usage

So, you need to untar `ort-<sha1>.tar` to your desired installation directory and then run the comntained shell script / batch file like

    ./cli/build/install/ort/bin/ort --help

(If `./cli/build/install/ort` was youo installation directory.)

**Comment by AnishaM7** [comment] 2023-02-22 16:53
Hi @sschuberth,

We got the resulting build output, when we untar  and execute ort --help , we get below error,
![image](https://user-images.githubusercontent.com/62882541/220699433-9068f6b3-fcb0-442f-8a43-becae93deee8.png)

**Comment by sschuberth** [comment] 2023-02-22 20:27
> when we untar and execute ort --help , we get below error

I just tried, and I cannot reproduce this. These were my steps:

* `./gradlew :cli:distTar`
* `tar -xf cli/build/distributions/ort-5692ae1f88.tar`
* `ort-5692ae1f88/bin/ort --help`

Which did output the help as expected.
