### ISSUE TITLE
Duplicate: Support for PNPM package manager

### ISSUE THREAD

**Issue by timo-HERE** [oss-review-toolkit/ort#5642] opened 2022-08-09 20:40 UTC
PNPM is addressing some shortcomings of npm and yarn and is used by some teams, so would be nice to add support for it.
* https://pnpm.io/feature-comparison
* PNPM uses pnpm-lock.yaml as lockfile

**Comment by MarcelBochtler** [comment] 2022-08-10 08:12
Hi @timo-HERE,
PNPM is already supported since https://github.com/oss-review-toolkit/ort/pull/5611.

**Comment by tsteenbe** [comment] 2022-08-10 15:02
@timo-HERE  Do you agree we can close this issue?

**Comment by timo-HERE** [comment] 2022-08-10 15:17
Yes, this can be closed for sure. 
I need to learn how to do use the search. I did not get any results yesterday, but I should have found all these; https://github.com/oss-review-toolkit/ort/issues?q=pnpm

**Comment by MarcelBochtler** [comment] 2022-08-10 15:20
Closed as this is a duplicate of https://github.com/oss-review-toolkit/ort/issues/2024

**Closed** 2022-08-10 15:19 UTC
Labels: duplicate
