### ISSUE TITLE
How to suppress the error "AnalyzerResult contains packages that are also projects."

### ISSUE THREAD

**Issue by mawl** [oss-review-toolkit/ort#5721] opened 2022-08-31 08:58 UTC
Hey,

How can we suppress following error concerning npm dependencies in a monorepo? Some of the dependencies are also projects in it.

```
07:18:50.479 [DefaultDispatcher-worker-4] ERROR org.ossreviewtoolkit.analyzer.AnalyzerResultBuilder - Multiple projects with the same id 'Yarn2::client:0.1.0' found. 
Not adding the project defined in 'https://same-url/package.json' to the analyzer results as it duplicates the project defined in 'https://same-url/package.json'.
Exception in thread "main" java.lang.IllegalArgumentException: AnalyzerResult contains packages that are also projects.
Duplicates: '[Identifier(type=NPM, namespace=@foo, name=some-library, version=0.1.15)]'.
	at org.ossreviewtoolkit.analyzer.AnalyzerResultBuilder.build(AnalyzerResultBuilder.kt:49)
	at org.ossreviewtoolkit.analyzer.AnalyzerState.buildResult(Analyzer.kt:250)
	at org.ossreviewtoolkit.analyzer.Analyzer.analyzeInParallel(Analyzer.kt:169)
	at org.ossreviewtoolkit.analyzer.Analyzer.analyze(Analyzer.kt:116)
	at org.ossreviewtoolkit.cli.commands.AnalyzerCommand.run(AnalyzerCommand.kt:284)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
	at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:81)
Evaluate
```

https://github.com/oss-review-toolkit/ort/blob/30ddfedb0cb9133836d4a33ff52aafeecbfdd9cd/analyzer/src/main/kotlin/AnalyzerResultBuilder.kt#L53

**Comment by nicorikken** [comment] 2022-09-05 15:22
I ran into the same issue unintentionally as the conflict sees to come from a directory I excluded, so I'm interested in other ways to work around this error.

Perhaps in the mono-repo setup you can scan all projects (subdirectories) separately to avoid the issue of duplicate dependencies?

**Comment by nicorikken** [comment] 2022-09-06 05:23
I got an answer through chat for my situation by @sschuberth that clarified the inner workings for me:

> As usual (in ORT), excludes don't actually prevent the analysis. ORT still tries to run the analysis and only marks the results of the analysis as excluded. Which means the consistency check you're running into is still executed.

**Comment by mnonnenmacher** [comment] 2022-09-06 19:05
This check was introduced in df84062 because if the analyzer result contains projects and packages with the same identifier this can lead to unexpected behavior in later steps. It usually indicates an issue in the package manager implementation which did not correctly identify a project dependency.

@mawl @nicorikken Please provide example projects that reproduce this issue so that we can identify the root cause.

**Comment by mawl** [comment] 2022-09-09 09:32
Here is an example project reproducing this issue.

[package-project.zip](https://github.com/oss-review-toolkit/ort/files/9534206/package-project.zip)

We had to use a local package approach for that as we usually publish our packages to our private registry.

**Comment by mawl** [comment] 2022-09-26 11:38
@mnonnenmacher: I have provided an example. Do you have any news for us concerning the progress? Thanks.

**Comment by mawl** [comment] 2022-12-30 12:28
@mnonnenmacher, @sschuberth: can you please check the example? We have a few monorepos in our company where we would like to have ORT to work for, too. Have a good New Year :)

**Comment by sschuberth** [comment] 2022-12-30 13:51
I haven't checked, but my hunch is that this happens because the monorepo contains both the source code to a package (which ORT treats as a project then), *and* another project is consuming the (binary) artifact for that package as a dependency (so here ORT treats it as a package). However, the id is the same in both cases. And that's something ORT does not currently support: Refer to the same id once as a project and once as a package / dependency within the same analysis.

**Comment by sschuberth** [comment] 2022-12-30 14:07
BTW, as of https://github.com/oss-review-toolkit/ort/pull/6241 you should actually also get a better error message in this case.

**Comment by mawl** [comment] 2023-01-20 08:16
During scan phase it is possible to exclude PROJECTs from scanning. Wouldn't it be possible to implement the same option for the analyze phase?

Usage: ort scan [OPTIONS]
  Run external license / copyright scanners.
Input Options:
...
  --package-types [PACKAGE|PROJECT]
                                   A comma-separated list of the package types
                                   from the ORT file's analyzer result to
                                   limit scans to. (default: [PACKAGE,
                                   PROJECT])
...

**Comment by sschuberth** [comment] 2023-01-20 11:28
> Wouldn't it be possible to implement the same option for the analyze phase as a workaround, like not treating them?

See https://github.com/oss-review-toolkit/ort/issues/5968 😉

**Comment by sschuberth** [comment] 2023-02-08 20:56
> > Wouldn't it be possible to implement the same option for the analyze phase as a workaround, like not treating them?
> 
> See #5968 😉

The PR has been merged, which answers the question on how to suppress the error by skipping paths with duplicate project / package ids.

**Closed by sschuberth** 2023-02-08 20:56 UTC
Labels: question, analyzer
