### ISSUE TITLE
Scanner expects master revision

### ISSUE THREAD

**Issue by bennati** [oss-review-toolkit/ort#6156] opened 2022-12-02 09:21 UTC
When scanning https://github.com/protocolbuffers/protobuf/commit/11bc195441adfbc87ff0349f1c4be7a239d1daad
The scanner hangs for 3h and throws 40 exceptions about 'master' branch not being found in https://github.com/microsoft/dotnet.
The Dotnet project has 'main' as the principal branch, and protobuf configuration does not mention 'master' anywhere, so it looks like the ORT scanner is expecting 'master' unless otherwise specified.

Example exception:
```
java.io.IOException: Could not resolve revision for package 'NuGet::Microsoft.NETFramework.ReferenceAssemblies.net40:1.0.0-preview.2' with VcsInfo(type=Git, url=https://github.com/Microsoft/dotnet.git, revision=master, path=releases/reference-assemblies):
	Discarding revision 'master' because the requested VCS path 'releases/reference-assemblies' does not exist.
	at org.ossreviewtoolkit.scanner.provenance.DefaultPackageProvenanceResolver$resolveVcs$6.invoke(PackageProvenanceResolver.kt:270)
	at org.ossreviewtoolkit.scanner.provenance.DefaultPackageProvenanceResolver$resolveVcs$6.invoke(PackageProvenanceResolver.kt:207)
	at org.ossreviewtoolkit.scanner.utils.DefaultWorkingTreeCache.use(WorkingTreeCache.kt:65)
	at org.ossreviewtoolkit.scanner.utils.DefaultWorkingTreeCache$use$1.invokeSuspend(WorkingTreeCache.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.ossreviewtoolkit.scanner.provenance.DefaultPackageProvenanceResolver.resolveProvenance(PackageProvenanceResolver.kt:85)
	at org.ossreviewtoolkit.scanner.Scanner$resolvePackageProvenances$duration$1$1$1$1.invokeSuspend(Scanner.kt:176)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
org.eclipse.jgit.api.errors.TransportException: Remote does not have refs/heads/master available for fetch.
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:244)
	at org.ossreviewtoolkit.downloader.vcs.Git.updateWorkingTreeWithoutSubmodules-gIAlu-s(Git.kt:203)
	at org.ossreviewtoolkit.downloader.vcs.Git.access$updateWorkingTreeWithoutSubmodules-gIAlu-s(Git.kt:68)
	at org.ossreviewtoolkit.downloader.vcs.Git$updateWorkingTree$1.invoke-IoAF18A(Git.kt:178)
	at org.ossreviewtoolkit.downloader.vcs.Git$updateWorkingTree$1.invoke(Git.kt:176)
	at org.ossreviewtoolkit.downloader.vcs.GitWorkingTree.useRepo(GitWorkingTree.kt:60)
	at org.ossreviewtoolkit.downloader.vcs.Git.updateWorkingTree-BWLJW6A(Git.kt:176)
	at org.ossreviewtoolkit.downloader.VersionControlSystem.updateWorkingTree-BWLJW6A$default(VersionControlSystem.kt:361)
	at org.ossreviewtoolkit.scanner.provenance.DefaultPackageProvenanceResolver$resolveVcs$6.invoke(PackageProvenanceResolver.kt:228)
	at org.ossreviewtoolkit.scanner.provenance.DefaultPackageProvenanceResolver$resolveVcs$6.invoke(PackageProvenanceResolver.kt:207)
	at org.ossreviewtoolkit.scanner.utils.DefaultWorkingTreeCache.use(WorkingTreeCache.kt:65)
	at org.ossreviewtoolkit.scanner.utils.DefaultWorkingTreeCache$use$1.invokeSuspend(WorkingTreeCache.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.ossreviewtoolkit.scanner.provenance.DefaultPackageProvenanceResolver.resolveProvenance(PackageProvenanceResolver.kt:85)
	at org.ossreviewtoolkit.scanner.Scanner$resolvePackageProvenances$duration$1$1$1$1.invokeSuspend(Scanner.kt:176)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: org.eclipse.jgit.errors.TransportException: Remote does not have refs/heads/master available for fetch.
	at org.eclipse.jgit.transport.FetchProcess.expandSingle(FetchProcess.java:427)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:169)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:103)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1405)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:233)
	... 29 more
```

**Comment by sschuberth** [comment] 2022-12-02 09:33
> Could not resolve revision for package 'NuGet::Microsoft.NETFramework.ReferenceAssemblies.net40:1.0.0-preview.2' with VcsInfo(type=Git, url=https://github.com/Microsoft/dotnet.git, revision=master, path=releases/reference-assemblies):

Looks like NuGet's metadata explicitly points us at `master`for this package, so I believe this to be a duplicate of https://github.com/oss-review-toolkit/ort/issues/4995.

The good news is that I already have a proposed solution for that in https://github.com/oss-review-toolkit/ort/pull/4997. The "bad" news is that @mnonnenmacher was asking for tests, and I did not have the time to write those yet 😉

**Closed** 2022-12-13 13:18 UTC
Labels: downloader
