### ISSUE TITLE
Memory consumption explodes on advisor and evaluator

### ISSUE THREAD

**Issue by borisbaldassari** [oss-review-toolkit/ort#6325] opened 2023-01-11 13:34 UTC
When trying to analyse Eclipse Jemo, the advisor, and then evaluator come to fail. The error message displayed with the reporter run is:

```
00:44:03.955 [main] INFO  org.ossreviewtoolkit.utils.scripting.ScriptRunner - Evaluating the script took 7m 2.842815630s.
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.HashSet.<init>(HashSet.java:163)
	at java.base/java.util.LinkedHashSet.<init>(LinkedHashSet.java:155)
	at kotlin.collections.SetsKt___SetsKt.minus(_Sets.kt:52)
	at org.ossreviewtoolkit.model.utils.FindingsMatcher.match(FindingsMatcher.kt:151)
	at org.ossreviewtoolkit.model.licenses.LicenseInfoResolver.resolveLocations(LicenseInfoResolver.kt:197)
	at org.ossreviewtoolkit.model.licenses.LicenseInfoResolver.createLicenseInfo(LicenseInfoResolver.kt:129)
	at org.ossreviewtoolkit.model.licenses.LicenseInfoResolver.resolveLicenseInfo(LicenseInfoResolver.kt:61)
	at org.ossreviewtoolkit.evaluator.RuleSet.packageRule(RuleSet.kt:79)
	at Script_rules$ruleSet$1.invoke(script.rules.kts:15)
	at Script_rules$ruleSet$1.invoke(script.rules.kts:8)
	at org.ossreviewtoolkit.evaluator.RuleSetKt.ruleSet(RuleSet.kt:165)
	at org.ossreviewtoolkit.evaluator.RuleSetKt.ruleSet$default(RuleSet.kt:160)
	at Script_rules.<init>(script.rules.kts:8)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at kotlin.script.experimental.jvm.BasicJvmScriptEvaluator.evalWithConfigAndOtherScriptsResults(BasicJvmScriptEvaluator.kt:105)
	at kotlin.script.experimental.jvm.BasicJvmScriptEvaluator.invoke$suspendImpl(BasicJvmScriptEvaluator.kt:47)
	at kotlin.script.experimental.jvm.BasicJvmScriptEvaluator.invoke(BasicJvmScriptEvaluator.kt)
	at kotlin.script.experimental.host.BasicScriptingHost$eval$1.invokeSuspend(BasicScriptingHost.kt:48)
	at kotlin.script.experimental.host.BasicScriptingHost$eval$1.invoke(BasicScriptingHost.kt)
	at kotlin.script.experimental.host.BasicScriptingHost$eval$1.invoke(BasicScriptingHost.kt)
	at kotlin.script.experimental.host.BasicScriptingHost$runInCoroutineContext$1.invokeSuspend(BasicScriptingHost.kt:36)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at kotlin.script.experimental.impl.RunSuspendKt.internalScriptingRunSuspend(runSuspend.kt:19)
	at kotlin.script.experimental.host.BasicScriptingHost.runInCoroutineContext(BasicScriptingHost.kt:36)
	at kotlin.script.experimental.host.BasicScriptingHost.eval(BasicScriptingHost.kt:46)
	at org.ossreviewtoolkit.utils.scripting.ScriptRunner.runScript(ScriptRunner.kt:71)
	at org.ossreviewtoolkit.evaluator.Evaluator.run(Evaluator.kt:56)
``` 

I could make it pass by adding `JAVA_OPTS="-Xmx10g"`, and then `JAVA_OPTS="-Xmx14g"` env var to the docker runs.

What is concerning is that the "analyzer" and "scanner" runs went well, and I see no reason for it to fail on the advisor if the previous steps went well. 

We use the docker images for the runs, and our full process can be seen in [our GitLab project](https://gitlab.eclipse.org/eclipsefdn/emo-team/eclipsefdn-ort) for more information. 

The full log of the failed execution can be found on [our Jenkins instance](https://foundation.eclipse.org/ci/infra/job/ort/job/Staging/job/staging_run_ort/95/console).

**Comment by mnonnenmacher** [comment] 2023-01-11 16:04
> See [this run](https://foundation.eclipse.org/ci/infra/job/ort/job/Staging/job/staging_run_ort/100/console) as an example.

It looks like the advisor silently fails because it should print a summary of the findings and the next step can't find the advisor result.

**Comment by mnonnenmacher** [comment] 2023-01-11 16:14
The analyzer finds 5 Maven and 2 NPM projects which is not an unusual number, I'm a bit surprised that this scan takes so much memory, the projects probably have a lot of dependencies. As a workaround you could try to run two separate scans for the Maven and NPM projects.

**Comment by borisbaldassari** [comment] 2023-01-12 12:55
Update: this kind of silent stop happened again on another project [1]. When looking deeper into it, I could correlate it with oom-kills showing up in /var/log/messages. So the silent fail is not on ORT. Still, this is a project code I've been analysing for months without any issue and the fact it now generates an oom-kill is.. strange, and concerning.

[1] https://github.com/eclipse/che

/cc @sschuberth The more I think about it, the more I come to agree with your initial though of a memory leak..

**Comment by borisbaldassari** [comment] 2023-01-12 13:25
FYI This is the memory consumption during the last failed execution. The run started around 1:22 and the oom-kill occurred at 4:28, as you can see.

![node-exporter-ort-staging](https://user-images.githubusercontent.com/5849071/212077652-56565043-3b86-48d9-bf9a-f07baac0fcfe.png)

**Comment by mnonnenmacher** [comment] 2023-01-12 15:29
Which command is causing these OOMs, is it always the advisor or different commands?

**Comment by borisbaldassari** [comment] 2023-01-12 15:37
This one (shown on the graph) occurred during the scanner phase.  \
Log can be seen [here](https://foundation.eclipse.org/ci/infra/job/ort/job/Staging/job/staging_run_ort/104/console) if it helps.

**Comment by borisbaldassari** [comment] 2023-01-12 18:32
So, to sum it up, and looking further at our [memory consumption](https://castalia.grafana.net/dashboard/snapshot/sQ4n7AfK3MH5l1xe2dsDtQUBGGF9YX3Z?orgId=1&refresh=30s), we can indeed see the memory peaks and oom kills are all related to the silent failures:
* technology.jemo crashed on 11 at 11.55 in the advisor phase [[jenkins](https://foundation.eclipse.org/ci/infra/job/ort/job/Staging/job/staging_run_ort/100/console)].
* ecd.che crashed on 11 at 13:56 in the scanner phase [[jenkins](https://foundation.eclipse.org/ci/infra/job/ort/job/Staging/job/staging_run_ort/102/console)].
* ecd.che crashed on 12 at 4:28 in the scanner phase [[jenkins](https://foundation.eclipse.org/ci/infra/job/ort/job/Staging/job/staging_run_ort/104/console)].

I've rebooted the server, just in case, and started other runs. Will let you know asap.

**Comment by sschuberth** [comment] 2023-01-26 13:07
> I've rebooted the server, just in case, and started other runs. Will let you know asap.

Any update here @borisbaldassari?

**Comment by borisbaldassari** [comment] 2023-01-31 07:16
Hi @sschuberth We doubled the memory on the production server (from 16 GB to 32 GB) and ooms no longer happen there. On the staging server however (which still has 16 GB of memory) ooms still happen. 

I have a strong feeling that the resources (memory, time to run) required to analyse a sample project have dramatically increased over the last 6 months -- but it's hard to tell as a lot has changed on our setup: we now use the Docker setup, with OSADL matrix computation / lists of licences, and upgraded ORT regularly. So, I'm not sure which step exactly made the setup significantly more resources-hungry. But as a matter of facts, I could analyse any of our projects 6 months ago on our servers, and now it takes 1.5 times longer and roughly 1.5 times the memory it used to. 

So this issue was solved by adding more memory, and can be closed from my side. If you want to keep it to track resources please feel free to reopen it. Thank you!

**Comment by sschuberth** [comment] 2023-10-30 21:34
> So this issue was solved by adding more memory, and can be closed from my side. If you want to keep it to track resources please feel free to reopen it.

I'm indeed going to close this for now as we're not anymore in a position to reproduce this.

**Closed by sschuberth** 2023-10-30 21:34 UTC
Labels: advisor, evaluator
