### ISSUE TITLE
Analyzer issue: All Packages have the same revision

### ISSUE THREAD

**Issue by pietbrauer** [oss-review-toolkit/ort#2704] opened 2020-06-09 12:40 UTC
Hello,

I am evaluating ORT using an Artsy Web App (https://github.com/artsy/artsy-wwwify) as my starting point. I analysed it using the latest master (122331e69d098820958869984a10023208990a7a) with `ort/cli/build/install/ort/bin/ort analyze -i source -o ort`.

I get [this result](https://github.com/oss-review-toolkit/ort/files/4752164/analyzer-result.yml.zip) where every package it found seems to have the same revision (`fb5a6e3808c93edadfe93468522ec55b4fe255a7`).
Doing the scanning it obviously fails because the revision in the repositories can not be found.

```
14:24:21.226 [ScanCode-1] WARN  org.ossreviewtoolkit.downloader.vcs.Git - Could not fetch with only a depth of 50: IOException: Running 'git checkout fb5a6e3808c93edadfe93468522ec55b4fe255a7' in 'ort/downloads/NPM/unknown/accepts/1.3.7' failed with exit code 128:
fatal: reference is not a tree: fb5a6e3808c93edadfe93468522ec55b4fe255a7

Falling back to fetching everything.
```

Is this a know issue or is there any workaround I could try?

Best,

Piet

**Comment by sschuberth** [comment] 2020-06-09 12:46
Please note the line "Falling back to fetching everything". So, what fails is just the performance-optimization to shallow-fetch only recent Git history. Also, the third-to-last line in the analyzer result says `has_issues: false`, so all should be fine.

**Comment by pietbrauer** [comment] 2020-06-09 12:49
Please search for `fb5a6e3808c93edadfe93468522ec55b4fe255a7` in the scan result and you will see what I mean: Every single NPM Package has the same vscRevision set.
The failing shallow clone is the first issue it encounters. It clones everything afterwards and fails to checkout the revision because it's not there.

**Comment by sschuberth** [comment] 2020-06-09 12:57
I see. Also strange that we get "Unkown" in `"Unmanaged::artsy-wwwify:fb5a6e3808c93edadfe93468522ec55b4fe255a7"` but *also* `"Yarn::artsy-wwwify:1.0.0"` as projects. Maybe @fviernau has an idea?

**Comment by fviernau** [comment] 2020-06-09 13:27
Hi @pietbrauer 

Could you please tell:
- the NPM version you're using
- if your log contains entries like: Resolving the package info for '$identifier' locally.

**Comment by pietbrauer** [comment] 2020-06-09 13:34
Sure, NPM version is `6.14.4`.
If you meant the output of the `analyze` command.

```bash
$ cli/build/install/ort/bin/ort analyze -i source -o ort
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by retrofit2.Platform (file:/Users/pietbrauer/Projects/ort/cli/build/install/ort/lib/retrofit-2.9.0.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
________ _____________________
\_____  \\______   \__    ___/ the OSS Review Toolkit, version 0.1.0-SNAPSHOT.
 /   |   \|       _/ |    |    Running 'analyze' under Java 12.0.2 on Mac OS X with
/    |    \    |   \ |    |    ORT_DATA_DIR = /Users/pietbrauer/.ort
\_______  /____|_  / |____|    SHELL = /bin/zsh
        \/       \/
More environment variables:
TERM = xterm-256color
JAVA_HOME = /Users/pietbrauer/.sdkman/candidates/java/current
GOPATH = /Users/pietbrauer/Documents/Projekte/go

The following package managers are activated:
	Bower, Bundler, Cargo, Conan, DotNet, GoDep, GoMod, Gradle, Maven, NPM, NuGet, PhpComposer, PIP, Pipenv, Pub, SBT, Stack, Yarn
Analyzing project path:
	source
Found 2 project(s) in total.
Writing analyzer result to 'ort/analyzer-result.yml'.
```

**Comment by fviernau** [comment] 2020-06-09 13:47
Hm, I have tried to reproduce it by
- doing a fresh clone of https://github.com/artsy/artsy-wwwify
- analyzing that clone directory

...without any success. Which were the exact steps you reproduced it with?

**Comment by pietbrauer** [comment] 2020-06-09 13:54
I did the exact same thing, just my copy was older (https://github.com/artsy/artsy-wwwify/commit/fb5a6e3808c93edadfe93468522ec55b4fe255a7).

I deleted the repository again, now I have a analyser-result where every revision is `fe6795435276da85ed4ec8aa2f461bc2e8c47488`.

**Comment by fviernau** [comment] 2020-06-09 14:01
Thanks! Could you also please share the operating system and whether you analyze the root directory of the repository?

It'd be useful to know whether entries like `Resolving the package info for '$identifier' locally.`
are contained in the debug log output, e.g. run `./cli/build/install/ort/bin/ort --debug analyze -i `...

**Comment by pietbrauer** [comment] 2020-06-09 14:04
Yes, it's full of these messages.

**Comment by fviernau** [comment] 2020-06-09 14:19
Thanks again. If I'm not missing anything there are just two root causes possible
- your package directories inside the `node_modules` directory are all symbolic links
- ORT's logic to determine whether a file is a symbolic link is broken

So could me do one more favor and run `npm install` in the directory containing the `package.json` and then tell whether the package directories within `node_modules` are actually symbolic links?

**Comment by pietbrauer** [comment] 2020-06-09 14:22
Just did a fresh `yarn install` (as there is a `yarn.lock`).
The `node_modules` just contain regular directories:
<img width="903" alt="image" src="https://user-images.githubusercontent.com/759730/84159362-48eefb00-aa6d-11ea-923b-23bccb014bc2.png">

**Comment by fviernau** [comment] 2020-06-09 14:29
Thanks! Do you get symbolic links also when doing `npm install` (instead of `yarn install`)?
I'm asking for NPM as this is what ORT used when creating the buggy analyzer result, e.g. note that the identifiers of the packages all start with `NPM:`.

**Comment by fviernau** [comment] 2020-06-09 14:33
In case NPM also should not create symbolic links we could try #2707 as speculative fix.

**Comment by pietbrauer** [comment] 2020-06-10 07:25
I tried removing `node_modules` just to be super sure.

- using the `master` version I still got the same result (revision broken)
- using the `npm-minor-improvements` branch the `--debug` log changed, the revisions where found and the scanning commences 
```
08:32:27.530 [Analyzer-1] DEBUG org.ossreviewtoolkit.analyzer.managers.Npm - Found a 'package.json' file in 'source/node_modules/acorn-globals/node_modules/acorn'.
08:32:27.531 [Analyzer-1] DEBUG org.ossreviewtoolkit.analyzer.managers.Npm - Resolving the package info for 'acorn@6.3.0' via NPM registry.
```

**Comment by fviernau** [comment] 2020-06-10 09:12
@pietbrauer great, thanks!
Then I'd just use my PR as fix for this, I just amended it slightly.

Just out of curiosity - regarding the path you passed to `ort analyze -i` as input directory: was any directory contained in that path a symbolic link by any chance?

**Comment by pietbrauer** [comment] 2020-06-10 09:13
I didn't find any directory that was a symbolic link, that's what is weird to me…

**Comment by fviernau** [comment] 2020-06-10 09:15
That's strange. I only have Linux available here so I cannot reproduce the OSX case unfortunately.

**Comment by sschuberth** [comment] 2020-06-10 10:24
> I didn't find any directory that was a symbolic link, that's what is weird to me…

Does macOS' Finder even display symbolic links differently from regular files? I.e. can it be that you simply didn't notice files to be links in reality?

**Closed** 2020-06-10 10:24 UTC
Labels: analyzer, bug

**Comment by pietbrauer** [comment] 2020-06-10 11:24
Yes, they would look like this (with an arrow):
<img width="213" alt="image" src="https://user-images.githubusercontent.com/759730/84262260-9e82e080-ab1d-11ea-950e-c955b0b6fb58.png">
