### ISSUE TITLE
Huge memory consumption during scanning step

### ISSUE THREAD

**Issue by fb33** [oss-review-toolkit/ort#3352] opened 2020-11-19 07:17 UTC
Hello

I use the ORT with a docker in a K8s infrastructure.
and I use postgres as storage backend for the scanner.

I need to allocate 14Gb to my pod to be able to run all the tools.
If I allocate "only" 10Gb, my pod is killed for excessive consumption when the scanner is running.
Here is an example file with the dependencies of a project : 
[analyzer-result.zip](https://github.com/oss-review-toolkit/ort/files/5564999/analyzer-result.zip)

Can an optimization be done on the ORT side on cache management or is it more on the scancode side?

Regards

**Comment by sschuberth** [comment] 2020-11-19 09:11
I believe we already have a report of this at https://github.com/oss-review-toolkit/ort/issues/3091, and we're generally aware of the issue. Performance improvements will be a focus for us in the next months / early next year. So, @fb33, would you agree to close this as a duplicate of https://github.com/oss-review-toolkit/ort/issues/3091?

**Comment by fb33** [comment] 2020-11-19 09:58
Yes, it's a question of memory consumption.
I thought #3248 had made some improvements in this case. So we could use ORT with 8GB max.
But I'm rebuilding a docker image with the master on November 10th, and I still had to allocate more than 10Gb for it to work well.
I attached a file to have a representative dataset for information.

We can close this issue.

**Comment by sschuberth** [comment] 2020-11-19 10:19
Well, https://github.com/oss-review-toolkit/ort/issues/3248 was more about addressing memory issues we saw in the *analyzer* phase for Android projects. However, as the root cause for the memory issues in the *scanner* probably is a different one, I'm not surprised that you had to increase memory even more.

As agreed, closing this to track the topic in the linked issue.

**Closed by sschuberth** 2020-11-19 10:19 UTC
Labels: bug, scanner
