### ISSUE TITLE
Incomplete/Incorrect SPDX report from Unmanaged package manager

### ISSUE THREAD

**Issue by kikofernandez** [oss-review-toolkit/ort#9352] opened 2024-10-30 08:02 UTC
### Describe the bug

I am trying to generate a SPDX SBOM for the Erlang programming language.

I have followed the documentation for getting an `analyzer-result.json` and a scan `scan-result.json` file.
The scan contains plenty of information (3.3 MB). When I generate a SPDX report, I get a SPDX report that looks empty

### To Reproduce

1. Clone repo 
    `git clone https://github.com/erlang/otp`
2. Run analysis
    `ort analyze -i otp -o otp -f JSON`
3. Run scanner
    `ort scan -f JSON -i otp/analyzer-result.json -o otp`
4. Generate SPDX report (the last two flags where recommended by @tsteenbe 👍🏾 )
    `ort report -i otp/scan-result.json -o otp -f SpdxDocument -O SpdxDocument=output.file.formats=json,yaml -O SpdxDocument=file.information.enabled=true`
5. See error
    I expected to see a source SBOM where every file analysed is included in the SBOM.
    Instead, I get the following, where I have omitted the COPYRIGHT due to being quite long.

### Console / log output

Generated SPDX SBOM

```
{
  "SPDXID" : "SPDXRef-DOCUMENT",
  "spdxVersion" : "SPDX-2.2",
  "creationInfo" : {
    "created" : "2024-10-30T07:42:02Z",
    "creators" : [ "Tool: ort-37.0.0" ],
    "licenseListVersion" : "3.25.0"
  },
  "name" : "Unnamed document",
  "dataLicense" : "CC0-1.0",
  "documentNamespace" : "spdx://aa3cf453-099a-43cc-9de6-ce6d9265c69e",
  "documentDescribes" : [ "SPDXRef-Project-Unmanaged-otp-75d1c4e37f883ab08a8f5bc1657848830246e050" ],
  "packages" : [ {
    "SPDXID" : "SPDXRef-Project-Unmanaged-otp-75d1c4e37f883ab08a8f5bc1657848830246e050",
    "copyrightText" : "<<Long Copyright that I omit>>",
    "downloadLocation" : "NONE",
    "filesAnalyzed" : false,
    "homepage" : "NONE",
    "licenseConcluded" : "NOASSERTION",
    "licenseDeclared" : "NOASSERTION",
    "name" : "otp",
    "summary" : "NONE",
    "versionInfo" : "75d1c4e37f883ab08a8f5bc1657848830246e050"
  } ]
}
```

### Environment

Output of the `ort requirements -l commands` command:

```
> bin/ort requirements -l commands

Hoplite is configured to infer which sealed type to choose by inspecting the config values at runtime. This behaviour is now deprecated in favour of explicitly specifying the type through a discriminator field. In 3.0 this new behavior will become the default. To enable this behavior now (and disable this warning), invoke withExplicitSealedTypes() on the ConfigLoaderBuilder.
 ______________________________                                                        
/        \_______   \__    ___/ The OSS Review Toolkit, version 37.0.0,                
|    |   | |       _/ |    |    built with JDK 21.0.4+7-LTS, running under Java 21.0.5.
|    |   | |    |   \ |    |    Executing 'requirements' as 'XXXX' on Linux         
\________/ |____|___/ |____|    with 8 CPUs and a maximum of 7948 MiB of memory.       
                                                                                       
Environment variables:                                                                
ORT_CONFIG_DIR = /home/XXXX/.ort/config                                            
ORT_DATA_DIR = /home/XXXX/.ort                                                     
HOME = /home/XXXX                                                                  
SHELL = /bin/bash                                                                     
TERM = xterm-256color                                                                 
JAVA_HOME = /usr/lib/jvm/jdk-21.0.5-oracle-x64                                        
                                                                                      
Looking for ORT configuration in the following file:
        /home/XXXXX/.ort/config/config.yml

Scanners:
        - Askalono: Requires 'askalono' in no specific version. Tool not found.
        - BoyterLc: Requires 'lc' in no specific version. Tool not found.
        - Licensee: Requires 'licensee' in no specific version. Tool not found.
        * ScanCode: Requires 'scancode' in version >=3.0.0. Found version 32.2.1.

PackageManagers:
        - Bazel: Requires 'bazel' in version >=7.0.0. Tool not found.
        - Bower: Requires 'bower' in version >=1.8.8. Tool not found.
        - Cargo: Requires 'cargo' in no specific version. Tool not found.
        - CocoaPods: Requires 'pod' in version >=1.11.0. Tool not found.
        - Composer: Requires 'composer' in version >=1.5.0. Tool not found.
        - Conan: Requires 'conan' in version >=1.44.0 and <2.0.0. Tool not found.
        + GoMod: Requires 'go' in version >=1.21.1. Found version 1.18.1.
        * Npm: Requires 'npm' in version >=6.0.0 and <11.0.0. Found version 10.5.0.
        - NuGetInspector: Requires 'nuget-inspector' in no specific version. Tool not found.
        - Pipenv: Requires 'pipenv' in version >=2018.10.9. Tool not found.
        - Pnpm: Requires 'pnpm' in version >=5.0.0 and <10.0.0. Tool not found.
        - Poetry: Requires 'poetry' in no specific version. Tool not found.
        - Pub: Requires 'dart' in version >=2.10.0. Tool not found.
        * PythonInspector: Requires 'python-inspector' in version >=0.9.2. Found version 0.12.0.
        - Sbt: Requires 'sbt' in no specific version. Tool not found.
        - Stack: Requires 'stack' in version >=2.1.1. Tool not found.
        - SwiftPm: Requires 'swift' in no specific version. Tool not found.
        - Yarn: Requires 'yarn' in version >=1.3.0 and <1.23.0. Tool not found.

VersionControlSystems:
        * Git: Requires 'git' in version >=2.29.0. Found version 2.34.1.
        - GitRepo: Requires 'repo' in no specific version. Tool not found.
        - Mercurial: Requires 'hg' in no specific version. Tool not found.

Prefix legend:
        - The tool was not found in the PATH environment.
        + The tool was found in the PATH environment, but not in the required version.
        * The tool was found in the PATH environment in the required version.

ScanCode license texts found in '/home/XXXX/Code/venv/lib64/python3.10/site-packages/licensedcode/data/licenses'.

Not all tools requirements were satisfied:
        ! Some tools were not found in their required versions.
        ! Some tools were not found at all.

```

*And* specify (relevant parts of) your ORT configuration (`config.yml`):

NOTHING

### Additional context

I am running from the latest binary.

**Comment by tsteenbe** [comment] 2024-10-31 09:13
Attaching [scan-result.zip](https://github.com/user-attachments/files/17585528/scan-result.zip) to help with debugging the issue

**Comment by sschuberth** [comment] 2024-10-31 09:56
I'll take a look as I have some SPDX-related stuff in the pipeline anyway.

**Comment by sschuberth** [comment] 2024-11-01 11:03
Since we only have a single project-package here from the "Unmanaged" package manager, this actually seems to be a duplicate of https://github.com/oss-review-toolkit/ort/issues/8485 to me. Let's close this in favor of continuing the discussion there.

**Closed by sschuberth** 2024-11-01 11:03 UTC
Labels: duplicate, reporter, spdx-utils

**Comment by kikofernandez** [comment] 2024-11-01 12:24
makes sense, thanks! I will move myself to that issue :)
