### ISSUE TITLE
Scanner: The ScanCode `maxVersion` parameter ignores patch version

### ISSUE THREAD

**Issue by zhernovs** [oss-review-toolkit/ort#4789] opened 2021-12-01 15:51 UTC
I'm trying to set the ScanCode version range to use for cache search so that only cache for version `3.2.1-rc2` is taken into account. 
The ort.conf has following entry: 
```
  scanner {

    options {
      ScanCode {
        minVersion = "3.2.1-rc2"
        maxVersion = "3.2.1-rc3"
      }
    }
  }
```
With these values ORT can't find cache entry
```
org.ossreviewtoolkit.scanner.scanners.scancode.ScanCode - Found stored scan results for 0 packages and ScannerCriteria(regScannerName=ScanCode, minVersion=3.2.1-rc2, maxVersion=3.2.1-rc3, configMatcher=(kotlin.String) -> kotlin.Boolean)
```

The same happens for `maxVersion = "3.2.2"`
```
org.ossreviewtoolkit.scanner.scanners.scancode.ScanCode - Found stored scan results for 0 packages and ScannerCriteria(regScannerName=ScanCode, minVersion=3.2.1-rc2, maxVersion=3.2.2, configMatcher=(kotlin.String) -> kotlin.Boolean).
```

Only `maxVersion = "3.3.0"` works as expected:
```
org.ossreviewtoolkit.scanner.scanners.scancode.ScanCode - Found stored scan results for 14 packages and ScannerCriteria(regScannerName=ScanCode, minVersion=3.2.1-rc2, maxVersion=3.3.0, configMatcher=(kotlin.String) -> kotlin.Boolean).
```

I assume there is a bug that cause ORT to ignore patch version of the `maxVersion` parameter when searching in the cache and work with major.minor versions only.

**Comment by sschuberth** [comment] 2021-12-01 19:50
Thanks for the report. While I'd not expect `maxVersion = "3.2.1-rc3"` to work (as there are no semantic attached to the string "rc" in Semver, so Semver4j does not know that "rc3" is more recent than "rc2"), I *would* expect `maxVersion = "3.2.2"` to work.

While looking around for the cause, I cleaned stuff up a bit and added a test in https://github.com/oss-review-toolkit/ort/pull/4791/commits/e8f21a0ace5e5cdfb03641691c761391ae08cc20, but that test actually succeeds, so I'm not sure what going wrong yet.

**Comment by sschuberth** [comment] 2024-06-03 09:11
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.

**Closed by sschuberth** 2024-06-03 09:11 UTC
Labels: bug, scanner, configuration
