### ISSUE TITLE
dependency_graphs: empty node '{ }' instead of '{ "pkg" : 0 }'

### ISSUE THREAD

**Issue by bruzzlerli** [oss-review-toolkit/ort#5729] opened 2022-09-02 08:14 UTC
I was analyzing a CSharp project. During the analysis of the 'dependency_graphs' I found that a node reference to package 0 was missing. It looks like the JSON exporter avoids to export the key 'pkg' on a zero value. (see image)

![grafik](https://user-images.githubusercontent.com/59935209/188095516-ac1c857e-9f21-4e20-80b8-376213b47834.png)

**Comment by sschuberth** [comment] 2022-09-02 09:47
@oheger-bosch is this a [NodeKey](https://github.com/oss-review-toolkit/ort/blob/26e60c4288f5ef458d89ba574d8474e83b08d933/model/src/main/kotlin/utils/DependencyGraphBuilder.kt#L464-L467) object being serialized here?

**Comment by mnonnenmacher** [comment] 2022-09-07 20:26
This is a `DependencyGraphNode` object, the reason is the `@JsonInclude(JsonInclude.Include.NON_DEFAULT)` class annotation. I just confirmed this using this code:

```kotlin
    val node1 = DependencyGraphNode(0)
    val node2 = DependencyGraphNode(1)

    fun toJson(value: Any) = jsonMapper.writerWithDefaultPrettyPrinter().writeValueAsString(value)

    println(toJson(node1))
    println(toJson(node2))

    println(jsonMapper.readValue<DependencyGraphNode>(toJson(node1)))
    println(jsonMapper.readValue<DependencyGraphNode>(toJson(node2)))
```

However, this is not an issue as the node is deserialized correctly as the output of above code shows:

```
{ }
{
  "pkg" : 1
}
DependencyGraphNode(pkg=0, fragment=0, linkage=DYNAMIC, issues=[])
DependencyGraphNode(pkg=1, fragment=0, linkage=DYNAMIC, issues=[])
```

I will close this issue as it is working correctly within ORT and the result files are not supposed to be parsed by third-party code.

@bruzzlerli If you want to parse the ORT output in another tool consider using the `EvaluatedModelReporter` or converting the result file to the dependency tree format using the helper-cli, see `orth set-dependency-representation --help`.

**Closed by mnonnenmacher** 2022-09-07 20:26 UTC
Labels: bug, analyzer
