### ISSUE TITLE
Support S3 as storage backend for the scan results cache

### ISSUE THREAD

**Issue by mnonnenmacher** [oss-review-toolkit/ort#752] opened 2018-08-08 09:45 UTC
Currently only Artifactory is supported as a storage backend to cache scan results. Also support S3 as an alternative.

**Comment by sschuberth** [comment] 2018-09-20 13:50
Closing as a duplicate of https://github.com/heremaps/oss-review-toolkit/issues/730.

**Closed by sschuberth** 2018-09-20 13:50 UTC
Labels: duplicate, good first issue, scanner
